services:
  backend:
    build:
      context: ./app/Backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    build:
      context: ./app/Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://${HOST_IP:-localhost}:3001/api/v1
      - HOST_IP=${HOST_IP:-}
    depends_on:
      - backend
