import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1780442077495 implements MigrationInterface {
  name = 'InitialSchema1780442077495';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Creación de todas las tablas del sistema

    await queryRunner.query(`
      CREATE TABLE sedes (
        id_sede INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre varchar(100) NOT NULL,
        direccion text,
        telefono varchar(20),
        hora_apertura time,
        hora_cierre time,
        esta_habilitada boolean NOT NULL DEFAULT true,
        created_by int,
        updated_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT chk_horario_sede CHECK (hora_cierre != hora_apertura)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE roles (
        id_rol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_rol varchar(80) NOT NULL UNIQUE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE marcas (
        id_marca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre varchar(100) NOT NULL UNIQUE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE categorias (
        id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_categoria varchar(100) NOT NULL UNIQUE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE estados_reparacion (
        id_estado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre varchar(30) NOT NULL UNIQUE,
        descripcion text,
        orden int NOT NULL,
        es_final boolean NOT NULL DEFAULT false
      )
    `);

    await queryRunner.query(`
      CREATE TABLE proveedores (
        id_proveedor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ruc varchar(15) NOT NULL UNIQUE,
        razon_social varchar(200) NOT NULL,
        contacto_nombre varchar(100),
        telefono varchar(20),
        updated_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(`
      CREATE TABLE empleados (
        id_empleado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_sede int,
        tipo_documento varchar(20) NOT NULL,
        nro_documento varchar(30) NOT NULL,
        nombre_completo varchar(150) NOT NULL,
        telefono varchar(20),
        sueldo_semanal_soles decimal(10, 2) NOT NULL CHECK (sueldo_semanal_soles >= 0),
        estado varchar(20) NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo', 'suspendido')),
        es_extranjero boolean DEFAULT false,
        direccion_completa text,
        password_hash varchar(255) NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz,
        created_by int,
        CONSTRAINT uq_empleado_doc UNIQUE (tipo_documento, nro_documento)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE empleado_roles (
        id_empleado int NOT NULL,
        id_rol int NOT NULL,
        PRIMARY KEY (id_empleado, id_rol)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE clientes (
        id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tipo_documento varchar(20) NOT NULL,
        nro_documento varchar(30) NOT NULL,
        nombre_completo varchar(150) NOT NULL,
        telefono varchar(20),
        direccion_completa text,
        es_extranjero boolean DEFAULT false,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz,
        CONSTRAINT uq_cliente_doc UNIQUE (tipo_documento, nro_documento)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE items (
        id_item INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tipo varchar(15) NOT NULL CHECK (tipo IN ('producto', 'repuesto')),
        sku varchar(50) NOT NULL UNIQUE,
        nombre varchar(150) NOT NULL,
        id_marca int,
        id_categoria int,
        modelo varchar(100),
        calidad varchar(30),
        especificaciones jsonb,
        precio_compra_actual decimal(12, 2) NOT NULL CHECK (precio_compra_actual >= 0),
        precio_venta_actual decimal(12, 2) NOT NULL CHECK (precio_venta_actual >= 0),
        updated_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT chk_precio_item CHECK (precio_venta_actual >= precio_compra_actual),
        CONSTRAINT chk_calidad_solo_repuesto CHECK (calidad IS NULL OR tipo = 'repuesto'),
        CONSTRAINT chk_categoria_solo_producto CHECK (id_categoria IS NOT NULL OR tipo = 'repuesto')
      )
    `);

    await queryRunner.query(`
      CREATE TABLE inventario_sedes (
        id_inventario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_sede int NOT NULL,
        id_item int NOT NULL,
        cantidad_actual int NOT NULL CHECK (cantidad_actual >= 0),
        stock_minimo int NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
        CONSTRAINT uq_inventario_sede_item UNIQUE (id_sede, id_item)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE movimientos_inventario (
        id_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_inventario int NOT NULL,
        tipo_movimiento varchar(30) NOT NULL CHECK (
          tipo_movimiento IN ('compra', 'venta', 'ajuste_manual', 'transferencia', 'reparacion', 'cambio')
        ),
        cantidad int NOT NULL,
        id_referencia int,
        id_empleado int,
        fecha_movimiento timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(`
      CREATE TABLE compras_refill (
        id_compra INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_empleado_refiller int NOT NULL,
        id_sede_destino int NOT NULL,
        id_proveedor int NOT NULL,
        fecha_compra timestamptz NOT NULL DEFAULT now(),
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz
      )
    `);

    await queryRunner.query(`
      CREATE TABLE detalle_compra_refill (
        id_detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_compra int NOT NULL,
        id_item int NOT NULL,
        cantidad_comprada int NOT NULL CHECK (cantidad_comprada > 0),
        costo_unidad decimal(12, 2) NOT NULL CHECK (costo_unidad >= 0),
        precio_venta_sugerido decimal(12, 2) NOT NULL CHECK (precio_venta_sugerido >= 0)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE promociones (
        id_promocion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre varchar(100) NOT NULL,
        dia_semana int CHECK (dia_semana BETWEEN 1 AND 7),
        fecha_inicio date,
        fecha_fin date,
        id_categoria_afectada int,
        id_item_afectado int,
        valor_descuento decimal(12, 2) NOT NULL CHECK (valor_descuento >= 0),
        tipo_descuento varchar(20) NOT NULL CHECK (tipo_descuento IN ('porcentaje', 'monto_fijo')),
        estado varchar(20) NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa', 'pausada', 'vencida', 'cancelada')),
        updated_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT chk_promo_exactamente_uno CHECK (
          (id_categoria_afectada IS NOT NULL AND id_item_afectado IS NULL)
          OR (id_categoria_afectada IS NULL AND id_item_afectado IS NOT NULL)
        ),
        CONSTRAINT chk_porcentaje_promo CHECK (tipo_descuento != 'porcentaje' OR valor_descuento <= 100),
        CONSTRAINT chk_fechas_promo CHECK (fecha_fin IS NULL OR fecha_fin > fecha_inicio)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE ventas (
        id_venta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fecha_emision timestamptz NOT NULL DEFAULT now(),
        id_cliente int,
        id_empleado int NOT NULL,
        id_sede int NOT NULL,
        monto_descuento decimal(12, 2) NOT NULL DEFAULT 0 CHECK (monto_descuento >= 0),
        tipo_descuento varchar(20) CHECK (tipo_descuento IN ('porcentaje','monto_fijo')),
        justificacion_descuento text,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz DEFAULT now()
      )
    `);

    await queryRunner.query(`
      CREATE TABLE detalle_venta (
        id_detalle_v INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_venta int NOT NULL,
        id_item int NOT NULL,
        cantidad int NOT NULL CHECK (cantidad > 0),
        precio_unitario_momento decimal(12, 2) NOT NULL CHECK (precio_unitario_momento >= 0),
        precio_normal_momento decimal(12, 2) NULL CHECK (precio_normal_momento >= 0),
        costo_unitario_momento decimal(12, 2) NOT NULL CHECK (costo_unitario_momento >= 0),
        importe decimal(12, 2) NOT NULL CHECK (importe >= 0),
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT uq_det_venta_item UNIQUE (id_venta, id_item)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE cambios_producto (
        id_cambio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_venta_origen int NOT NULL,
        id_garantia int,
        id_empleado int NOT NULL,
        id_sede int NOT NULL,
        id_item_devuelto int NOT NULL,
        cantidad int NOT NULL CHECK (cantidad > 0),
        precio_devuelto decimal(12,2) NOT NULL CHECK (precio_devuelto >= 0),
        id_item_entregado int NOT NULL,
        precio_entregado decimal(12,2) NOT NULL CHECK (precio_entregado >= 0),
        diferencia_cobrada decimal(12,2) NOT NULL DEFAULT 0 CHECK (diferencia_cobrada >= 0),
        metodo_pago_dif varchar(30) CHECK (metodo_pago_dif IN ('efectivo','tarjeta','transferencia','yape','plin','otro')),
        referencia_transaccion varchar(100),
        motivo varchar(50) NOT NULL CHECK (motivo IN ('defecto', 'garantia', 'otro')),
        detalle text,
        fecha_cambio timestamptz NOT NULL DEFAULT now(),
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT chk_cambio_items_distintos CHECK (id_item_devuelto != id_item_entregado),
        CONSTRAINT chk_metodo_requerido CHECK (diferencia_cobrada = 0 OR metodo_pago_dif IS NOT NULL),
        CONSTRAINT chk_diferencia_razonable CHECK (
          diferencia_cobrada <= GREATEST((precio_entregado - precio_devuelto) * cantidad, 0)
        )
      )
    `);

    await queryRunner.query(`
      CREATE TABLE reparaciones (
        id_reparacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fecha_ingreso timestamptz NOT NULL DEFAULT now(),
        id_cliente int NOT NULL,
        id_tecnico int NOT NULL,
        id_sede int NOT NULL,
        marca varchar(50),
        modelo varchar(50),
        imei varchar(15) CHECK (imei ~ '^[0-9]{15}$'),
        esta_encendido boolean,
        checklist_estado jsonb,
        diagnostico_tecnico text,
        id_estado int NOT NULL,
        fecha_terminado timestamptz,
        fecha_entrega_cliente timestamptz,
        monto_cotizado decimal(12, 2) CHECK (monto_cotizado IS NULL OR monto_cotizado >= 0),
        monto_descuento decimal(12, 2) NOT NULL DEFAULT 0 CHECK (monto_descuento >= 0),
        tipo_descuento varchar(20) CHECK (tipo_descuento IN ('porcentaje','monto_fijo')),
        justificacion_descuento text,
        fotos jsonb,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz DEFAULT now(),
        CONSTRAINT chk_fechas_rep CHECK (
          (fecha_terminado IS NULL OR fecha_terminado >= fecha_ingreso)
          AND (fecha_entrega_cliente IS NULL OR (fecha_terminado IS NOT NULL AND fecha_entrega_cliente >= fecha_terminado))
        )
      )
    `);

    await queryRunner.query(`
      CREATE TABLE reparacion_repuestos_usados (
        id_repuesto_u INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_reparacion int NOT NULL,
        id_item int NOT NULL,
        cantidad int NOT NULL CHECK (cantidad > 0),
        precio_cobrado decimal(12, 2) NOT NULL CHECK (precio_cobrado >= 0),
        costo_unitario_momento decimal(12, 2) NOT NULL CHECK (costo_unitario_momento >= 0)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE garantias (
        id_garantia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_venta int,
        id_reparacion int,
        fecha_inicio date NOT NULL,
        fecha_fin date NOT NULL,
        estado varchar(20) NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa', 'vencida', 'invalidada')),
        motivo_invalidacion text,
        updated_at timestamptz DEFAULT now(),
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT chk_garantia_xor CHECK (
          (id_venta IS NOT NULL AND id_reparacion IS NULL)
          OR (id_venta IS NULL AND id_reparacion IS NOT NULL)
        ),
        CONSTRAINT chk_fechas_garantia CHECK (fecha_fin > fecha_inicio)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE pagos (
        id_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_venta int,
        id_reparacion int,
        metodo_pago varchar(30) NOT NULL CHECK (
          metodo_pago IN ('efectivo', 'tarjeta', 'transferencia', 'yape', 'plin', 'otro')
        ),
        monto decimal(12, 2) NOT NULL CHECK (monto > 0),
        es_adelanto boolean NOT NULL DEFAULT false,
        fecha_pago timestamptz NOT NULL DEFAULT now(),
        referencia_transaccion varchar(100),
        CONSTRAINT chk_pago_xor CHECK (
          (id_venta IS NOT NULL AND id_reparacion IS NULL)
          OR (id_venta IS NULL AND id_reparacion IS NOT NULL)
        ),
        CONSTRAINT chk_adelanto_solo_reparacion CHECK (es_adelanto = false OR id_reparacion IS NOT NULL)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE boletas (
        id_boleta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        numero varchar(20) NOT NULL UNIQUE,
        fecha_emision timestamptz NOT NULL DEFAULT now(),
        id_venta int,
        id_reparacion int,
        total decimal(12, 2) NOT NULL CHECK (total >= 0),
        estado varchar(20) NOT NULL DEFAULT 'emitida' CHECK (estado = 'emitida'),
        url_pdf varchar(500),
        CONSTRAINT chk_boleta_xor CHECK (
          (id_venta IS NOT NULL AND id_reparacion IS NULL)
          OR (id_venta IS NULL AND id_reparacion IS NOT NULL)
        )
      )
    `);

    await queryRunner.query(`
      CREATE TABLE logs_sistema (
        id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fecha_hora timestamptz NOT NULL DEFAULT now(),
        id_empleado int,
        id_sede int,
        tipo_accion varchar(20) NOT NULL CHECK (
          tipo_accion IN (
            'creacion', 'actualizacion', 'eliminacion', 'cambio_estado',
            'cambio_precio', 'login', 'logout', 'error', 'anulacion'
          )
        ),
        tabla_afectada varchar(100) NOT NULL CHECK (
          tabla_afectada IN (
            'Sedes', 'Empleados', 'Clientes', 'Items', 'Inventario_Sedes',
            'Ventas', 'Detalle_Venta', 'Reparaciones', 'Reparacion_Repuestos_Usados',
            'Compras_Refill', 'Detalle_Compra_Refill', 'Promociones', 'Garantias',
            'Pagos', 'Boletas', 'Roles', 'Empleado_Roles', 'Marcas', 'Categorias',
            'Proveedores', 'Estados_Reparacion', 'Cambios_Producto'
          )
        ),
        tipo_referencia varchar(30) CHECK (
          tipo_referencia IN ('venta', 'compra', 'reparacion', 'ajuste', 'promocion', 'cambio', 'otro')
        ),
        id_referencia int,
        detalle_cambio text
      )
    `);

    await queryRunner.query(`
      CREATE TABLE refreshtokens (
        id BIGSERIAL PRIMARY KEY,
        id_empleado INTEGER NOT NULL,
        token_hash TEXT NOT NULL,
        expires_at TIMESTAMPTZ NOT NULL,
        revoked BOOLEAN NOT NULL DEFAULT false,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);

    // Foreign Keys

    await queryRunner.query(
      `ALTER TABLE refreshtokens ADD CONSTRAINT fk_refresh_empleado FOREIGN KEY (id_empleado) REFERENCES empleados (id_empleado) ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE empleados ADD CONSTRAINT fk_empleado_sede FOREIGN KEY (id_sede) REFERENCES sedes (id_sede)`,
    );
    await queryRunner.query(
      `ALTER TABLE empleado_roles ADD CONSTRAINT fk_emproles_empleado FOREIGN KEY (id_empleado) REFERENCES empleados (id_empleado) ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE empleado_roles ADD CONSTRAINT fk_emproles_rol FOREIGN KEY (id_rol) REFERENCES roles (id_rol) ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE items ADD CONSTRAINT fk_items_marca FOREIGN KEY (id_marca) REFERENCES marcas (id_marca)`,
    );
    await queryRunner.query(
      `ALTER TABLE items ADD CONSTRAINT fk_items_categoria FOREIGN KEY (id_categoria) REFERENCES categorias (id_categoria)`,
    );
    await queryRunner.query(
      `ALTER TABLE inventario_sedes ADD CONSTRAINT fk_inv_sede FOREIGN KEY (id_sede) REFERENCES sedes (id_sede)`,
    );
    await queryRunner.query(
      `ALTER TABLE inventario_sedes ADD CONSTRAINT fk_inv_item FOREIGN KEY (id_item) REFERENCES items (id_item)`,
    );
    await queryRunner.query(
      `ALTER TABLE movimientos_inventario ADD CONSTRAINT fk_movinv_inventario FOREIGN KEY (id_inventario) REFERENCES inventario_sedes (id_inventario)`,
    );
    await queryRunner.query(
      `ALTER TABLE movimientos_inventario ADD CONSTRAINT fk_movinv_empleado FOREIGN KEY (id_empleado) REFERENCES empleados (id_empleado)`,
    );
    await queryRunner.query(
      `ALTER TABLE compras_refill ADD CONSTRAINT fk_compra_empleado FOREIGN KEY (id_empleado_refiller) REFERENCES empleados (id_empleado)`,
    );
    await queryRunner.query(
      `ALTER TABLE compras_refill ADD CONSTRAINT fk_compra_sede FOREIGN KEY (id_sede_destino) REFERENCES sedes (id_sede)`,
    );
    await queryRunner.query(
      `ALTER TABLE compras_refill ADD CONSTRAINT fk_compra_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedores (id_proveedor)`,
    );
    await queryRunner.query(
      `ALTER TABLE detalle_compra_refill ADD CONSTRAINT fk_detcompra_compra FOREIGN KEY (id_compra) REFERENCES compras_refill (id_compra) ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE detalle_compra_refill ADD CONSTRAINT fk_detcompra_item FOREIGN KEY (id_item) REFERENCES items (id_item)`,
    );
    await queryRunner.query(
      `ALTER TABLE promociones ADD CONSTRAINT fk_promo_categoria FOREIGN KEY (id_categoria_afectada) REFERENCES categorias (id_categoria)`,
    );
    await queryRunner.query(
      `ALTER TABLE promociones ADD CONSTRAINT fk_promo_item FOREIGN KEY (id_item_afectado) REFERENCES items (id_item)`,
    );
    await queryRunner.query(
      `ALTER TABLE ventas ADD CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente) ON DELETE SET NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE ventas ADD CONSTRAINT fk_venta_empleado FOREIGN KEY (id_empleado) REFERENCES empleados (id_empleado)`,
    );
    await queryRunner.query(
      `ALTER TABLE ventas ADD CONSTRAINT fk_venta_sede FOREIGN KEY (id_sede) REFERENCES sedes (id_sede)`,
    );
    await queryRunner.query(
      `ALTER TABLE detalle_venta ADD CONSTRAINT fk_detventa_venta FOREIGN KEY (id_venta) REFERENCES ventas (id_venta) ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE detalle_venta ADD CONSTRAINT fk_detventa_item FOREIGN KEY (id_item) REFERENCES items (id_item)`,
    );
    await queryRunner.query(
      `ALTER TABLE reparaciones ADD CONSTRAINT fk_rep_estado FOREIGN KEY (id_estado) REFERENCES estados_reparacion (id_estado)`,
    );
    await queryRunner.query(
      `ALTER TABLE reparaciones ADD CONSTRAINT fk_rep_cliente FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente)`,
    );
    await queryRunner.query(
      `ALTER TABLE reparaciones ADD CONSTRAINT fk_rep_tecnico FOREIGN KEY (id_tecnico) REFERENCES empleados (id_empleado)`,
    );
    await queryRunner.query(
      `ALTER TABLE reparaciones ADD CONSTRAINT fk_rep_sede FOREIGN KEY (id_sede) REFERENCES sedes (id_sede)`,
    );
    await queryRunner.query(
      `ALTER TABLE reparacion_repuestos_usados ADD CONSTRAINT fk_reprepuestos_rep FOREIGN KEY (id_reparacion) REFERENCES reparaciones (id_reparacion) ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE reparacion_repuestos_usados ADD CONSTRAINT fk_reprepuestos_item FOREIGN KEY (id_item) REFERENCES items (id_item)`,
    );
    await queryRunner.query(
      `ALTER TABLE garantias ADD CONSTRAINT fk_garantia_venta FOREIGN KEY (id_venta) REFERENCES ventas (id_venta) ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE garantias ADD CONSTRAINT fk_garantia_rep FOREIGN KEY (id_reparacion) REFERENCES reparaciones (id_reparacion) ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE cambios_producto ADD CONSTRAINT fk_cambio_venta FOREIGN KEY (id_venta_origen) REFERENCES ventas (id_venta)`,
    );
    await queryRunner.query(
      `ALTER TABLE cambios_producto ADD CONSTRAINT fk_cambio_garantia FOREIGN KEY (id_garantia) REFERENCES garantias (id_garantia) ON DELETE SET NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE cambios_producto ADD CONSTRAINT fk_cambio_empleado FOREIGN KEY (id_empleado) REFERENCES empleados (id_empleado)`,
    );
    await queryRunner.query(
      `ALTER TABLE cambios_producto ADD CONSTRAINT fk_cambio_sede FOREIGN KEY (id_sede) REFERENCES sedes (id_sede)`,
    );
    await queryRunner.query(
      `ALTER TABLE cambios_producto ADD CONSTRAINT fk_cambio_item_devuelto FOREIGN KEY (id_item_devuelto) REFERENCES items (id_item)`,
    );
    await queryRunner.query(
      `ALTER TABLE cambios_producto ADD CONSTRAINT fk_cambio_item_entregado FOREIGN KEY (id_item_entregado) REFERENCES items (id_item)`,
    );
    await queryRunner.query(
      `ALTER TABLE pagos ADD CONSTRAINT fk_pago_venta FOREIGN KEY (id_venta) REFERENCES ventas (id_venta) ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE pagos ADD CONSTRAINT fk_pago_rep FOREIGN KEY (id_reparacion) REFERENCES reparaciones (id_reparacion) ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE boletas ADD CONSTRAINT fk_boleta_venta FOREIGN KEY (id_venta) REFERENCES ventas (id_venta) ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE boletas ADD CONSTRAINT fk_boleta_rep FOREIGN KEY (id_reparacion) REFERENCES reparaciones (id_reparacion) ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE logs_sistema ADD CONSTRAINT fk_log_empleado FOREIGN KEY (id_empleado) REFERENCES empleados (id_empleado)`,
    );
    await queryRunner.query(
      `ALTER TABLE logs_sistema ADD CONSTRAINT fk_log_sede FOREIGN KEY (id_sede) REFERENCES sedes (id_sede)`,
    );
    await queryRunner.query(
      `ALTER TABLE sedes ADD CONSTRAINT fk_sedes_created_by FOREIGN KEY (created_by) REFERENCES empleados (id_empleado) ON DELETE SET NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE empleados ADD CONSTRAINT fk_empleados_created_by FOREIGN KEY (created_by) REFERENCES empleados (id_empleado) ON DELETE SET NULL`,
    );

    // Índices

    await queryRunner.query(
      `CREATE INDEX idx_ventas_sede_fecha ON ventas (id_sede, fecha_emision)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_ventas_cliente ON ventas (id_cliente)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_detalle_venta_venta ON detalle_venta (id_venta)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_det_venta_item ON detalle_venta (id_item)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_inv_item ON inventario_sedes (id_item)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_reparaciones_sede_fecha ON reparaciones (id_sede, fecha_ingreso)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_reparaciones_estado ON reparaciones (id_estado)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_reparaciones_cliente ON reparaciones (id_cliente)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_reparaciones_tecnico ON reparaciones (id_tecnico)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_rep_rep_usados_item ON reparacion_repuestos_usados (id_item)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_logs_fecha_hora ON logs_sistema (fecha_hora)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_logs_ref ON logs_sistema (tipo_referencia, id_referencia)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_mov_inv_fecha ON movimientos_inventario (fecha_movimiento)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_mov_inv_inventario ON movimientos_inventario (id_inventario, fecha_movimiento)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_item_espec_modelo ON items ((especificaciones->>'modelo'))`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_det_compra_item ON detalle_compra_refill (id_item)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_pagos_venta ON pagos (id_venta) WHERE id_venta IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_pagos_reparacion ON pagos (id_reparacion) WHERE id_reparacion IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_garantias_venta ON garantias (id_venta) WHERE id_venta IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_garantias_reparacion ON garantias (id_reparacion) WHERE id_reparacion IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_boletas_venta ON boletas (id_venta) WHERE id_venta IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_boletas_reparacion ON boletas (id_reparacion) WHERE id_reparacion IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_cambios_venta_origen ON cambios_producto (id_venta_origen)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_cambios_sede_fecha ON cambios_producto (id_sede, fecha_cambio)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_cambios_item_devuelto ON cambios_producto (id_item_devuelto)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_cambios_item_entregado ON cambios_producto (id_item_entregado)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_refresh_tokens_empleado ON refreshtokens (id_empleado)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_refresh_tokens_expiry ON refreshtokens (expires_at) WHERE revoked = false`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const indexes = [
      'idx_refresh_tokens_expiry',
      'idx_refresh_tokens_empleado',
      'idx_cambios_item_entregado',
      'idx_cambios_item_devuelto',
      'idx_cambios_sede_fecha',
      'idx_cambios_venta_origen',
      'idx_boletas_reparacion',
      'idx_boletas_venta',
      'idx_garantias_reparacion',
      'idx_garantias_venta',
      'idx_pagos_reparacion',
      'idx_pagos_venta',
      'idx_det_compra_item',
      'idx_item_espec_modelo',
      'idx_mov_inv_inventario',
      'idx_mov_inv_fecha',
      'idx_logs_ref',
      'idx_logs_fecha_hora',
      'idx_rep_rep_usados_item',
      'idx_reparaciones_tecnico',
      'idx_reparaciones_cliente',
      'idx_reparaciones_estado',
      'idx_reparaciones_sede_fecha',
      'idx_inv_item',
      'idx_det_venta_item',
      'idx_detalle_venta_venta',
      'idx_ventas_cliente',
      'idx_ventas_sede_fecha',
    ];
    for (const idx of indexes) {
      await queryRunner.query(`DROP INDEX IF EXISTS ${idx}`);
    }

    const tables = [
      'refreshtokens',
      'logs_sistema',
      'boletas',
      'pagos',
      'garantias',
      'cambios_producto',
      'reparacion_repuestos_usados',
      'reparaciones',
      'detalle_venta',
      'ventas',
      'promociones',
      'detalle_compra_refill',
      'compras_refill',
      'movimientos_inventario',
      'inventario_sedes',
      'items',
      'clientes',
      'empleado_roles',
      'empleados',
      'proveedores',
      'estados_reparacion',
      'categorias',
      'marcas',
      'roles',
      'sedes',
    ];
    for (const table of tables) {
      await queryRunner.query(`DROP TABLE IF EXISTS ${table} CASCADE`);
    }
  }
}
