-- ============================================================================
-- @Purpose: Esquema de base de datos para sistema de gestión de taller de
--           reparación de celulares con venta de productos y repuestos.
--           Soporta múltiples sedes, control de inventario por sede, compras
--           a proveedores (refill), ventas, reparaciones, garantías y pagos.
-- @Dialect: PostgreSQL 15+
-- @Convenciones:
--   - Nombres de tablas en PascalCase con snake_case para compuestas.
--   - Nombres de columnas en snake_case.
--   - PK: id_<entidad> autogenerada con IDENTITY.
--   - Timestamps: created_at (NOT NULL, DEFAULT now()), updated_at (nullable).
--   - Constraints con prefijo: pk_ / fk_ / uq_ / chk_ .
-- ============================================================================

-- ============================================================================
-- SECCIÓN 1: CATÁLOGO / TABLAS BASE
-- Tablas maestras que definen entidades de configuración y clasificación.
-- Deben poblarse primero (sin dependencias FK entre sí).
-- ============================================================================

-- @Purpose: Sedes físicas del negocio (tiendas / talleres).
-- Cada sede opera con su propio inventario y personal.
CREATE TABLE Sedes (
  id_sede INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL,
  direccion text,
  telefono varchar(20),
  hora_apertura time,                          -- Horario de apertura de la sede
  hora_cierre time,                            -- Horario de cierre de la sede
  updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_horario_sede CHECK (hora_cierre != hora_apertura)  -- Evita horario nulo o idéntico
);

-- @Purpose: Roles laborales asignables a empleados (ej: técnico, vendedor, admin).
CREATE TABLE Roles (
  id_rol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_rol varchar(80) NOT NULL UNIQUE
);

-- @Purpose: Marcas de productos y repuestos (ej: Samsung, Apple, Generic).
CREATE TABLE Marcas (
  id_marca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL UNIQUE
);

-- @Purpose: Categorías de productos (ej: pantallas, baterías, accesorios).
-- Solo aplica a items de tipo 'producto'; los repuestos no requieren categoría.
CREATE TABLE Categorias (
  id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_categoria varchar(100) NOT NULL UNIQUE
);

-- @Purpose: Estados del flujo de reparación (ej: recibido, diagnosticando, reparando, listo, entregado).
-- El campo `orden` define la secuencia y `es_final` indica si cierra el flujo.
CREATE TABLE Estados_Reparacion (
  id_estado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(30) NOT NULL UNIQUE,
  descripcion text,
  orden int NOT NULL,                          -- Secuencia ordinal en el flujo de trabajo
  es_final boolean NOT NULL DEFAULT false      -- TRUE si el estado cierra el proceso (ej: 'entregado')
);

-- @Purpose: Proveedores de productos y repuestos para compras de refill.
CREATE TABLE Proveedores (
  id_proveedor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ruc varchar(15) NOT NULL UNIQUE,
  razon_social varchar(200) NOT NULL,
  contacto_nombre varchar(100),
  telefono varchar(20),
  updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- SECCIÓN 2: PERSONAS
-- Entidades que representan a los actores del sistema: empleados y clientes.
-- ============================================================================

-- @Purpose: Empleados del negocio. Cada empleado pertenece a una sede y puede
--           tener uno o más roles (definidos en Empleado_Roles).
-- @BusinessRule: Si el tipo de documento es DNI, la dirección es obligatoria.
CREATE TABLE Empleados (
  id_empleado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sede int NOT NULL,                        -- Sede a la que pertenece el empleado
  tipo_documento varchar(20) NOT NULL,         -- DNI, CE, pasaporte, etc.
  nro_documento varchar(30) NOT NULL,
  nombre_completo varchar(150) NOT NULL,
  telefono varchar(20),
  sueldo_semanal_soles decimal(10, 2) NOT NULL CHECK (sueldo_semanal_soles >= 0),
  estado varchar(20) NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo', 'suspendido')),
  es_extranjero boolean DEFAULT false,
  direccion_completa text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz,
  CONSTRAINT uq_empleado_doc UNIQUE (tipo_documento, nro_documento),  -- Documento único por tipo
  CONSTRAINT chk_dni_direccion CHECK (
    NOT (
      tipo_documento = 'DNI'
      AND direccion_completa IS NULL           -- DNI peruano requiere dirección obligatoria
    )
  )
);

-- @Purpose: Relación muchos-a-muchos entre Empleados y Roles.
-- Un empleado puede tener múltiples roles (ej: técnico y vendedor).
CREATE TABLE Empleado_Roles (
  id_empleado int NOT NULL,
  id_rol int NOT NULL,
  PRIMARY KEY (id_empleado, id_rol)
);

-- @Purpose: Clientes del negocio (compradores y dueños de equipos en reparación).
-- @BusinessRule: Si el tipo de documento es DNI, la dirección es obligatoria.
CREATE TABLE Clientes (
  id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_documento varchar(20) NOT NULL,
  nro_documento varchar(30) NOT NULL,
  nombre_completo varchar(150) NOT NULL,
  telefono varchar(20),
  direccion_completa text,
  es_extranjero boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz,
  CONSTRAINT uq_cliente_doc UNIQUE (tipo_documento, nro_documento),
  CONSTRAINT chk_dni_direccion CHECK (
    NOT (
      tipo_documento = 'DNI'
      AND direccion_completa IS NULL
    )
  )
);

-- ============================================================================
-- SECCIÓN 3: INVENTARIO Y PRODUCTOS
-- Gestión de items (productos y repuestos), stock por sede y trazabilidad
-- de movimientos de inventario.
-- ============================================================================

-- @Purpose: Catálogo unificado de productos y repuestos.
--           - producto: se vende directamente, requiere categoría.
--           - repuesto: se usa en reparaciones, puede tener calidad (original, genérico, etc.).
-- @BusinessRule: precio_venta_actual >= precio_compra_actual (margen no negativo).
CREATE TABLE Items (
  id_item INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar(15) NOT NULL CHECK (tipo IN ('producto', 'repuesto')),
  sku varchar(50) NOT NULL UNIQUE,             -- Código único de inventario
  nombre varchar(150) NOT NULL,
  id_marca int,                                -- FK a Marcas (nullable para genéricos)
  id_categoria int,                            -- FK a Categorias (obligatorio para productos)
  modelo varchar(100),
  calidad varchar(30),                         -- Solo para repuestos: original, genérico, etc.
  especificaciones jsonb,                      -- Atributos flexibles en formato JSON (ej: color, capacidad)
  precio_compra_actual decimal(12, 2) NOT NULL CHECK (precio_compra_actual >= 0),
  precio_venta_actual decimal(12, 2) NOT NULL CHECK (precio_venta_actual >= 0),
  updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_precio_item CHECK (precio_venta_actual >= precio_compra_actual),
  CONSTRAINT chk_calidad_solo_repuesto CHECK (
    calidad IS NULL
    OR tipo = 'repuesto'                       -- La calidad solo aplica a repuestos
  ),
  CONSTRAINT chk_categoria_solo_producto CHECK (
    id_categoria IS NOT NULL
    OR tipo = 'repuesto'                       -- Los repuestos no requieren categoría
  )
);

-- @Purpose: Stock de cada item por sede. Una fila por combinación (sede, item).
--           `stock_minimo` permite generar alertas de reabastecimiento.
CREATE TABLE Inventario_Sedes (
  id_inventario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sede int NOT NULL,
  id_item int NOT NULL,
  cantidad_actual int NOT NULL CHECK (cantidad_actual >= 0),
  stock_minimo int NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
  CONSTRAINT uq_inventario_sede_item UNIQUE (id_sede, id_item)  -- Un solo registro de stock por sede+item
);

-- @Purpose: Bitácora de todos los movimientos de inventario (compras, ventas,
--           ajustes, transferencias entre sedes, consumo en reparaciones).
--           Permite auditoría completa y trazabilidad del stock.
CREATE TABLE Movimientos_Inventario (
  id_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_inventario int NOT NULL,                  -- FK a Inventario_Sedes
  tipo_movimiento varchar(30) NOT NULL CHECK (
    tipo_movimiento IN (
      'compra',                                -- Ingreso por compra a proveedor
      'venta',                                 -- Egreso por venta
      'ajuste_manual',                         -- Corrección manual de stock
      'transferencia',                         -- Movimiento entre sedes
      'reparacion'                             -- Consumo de repuesto en reparación
    )
  ),
  cantidad int NOT NULL,                       -- Positivo = ingreso, Negativo = egreso
  id_referencia int,                           -- ID de la entidad origen (venta, compra, reparación)
  id_empleado int,                             -- Empleado que realizó el movimiento
  fecha_movimiento timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- SECCIÓN 4: COMPRAS Y ABASTECIMIENTO (REFILL)
-- Registro de compras a proveedores para reabastecer el inventario de una sede.
-- ============================================================================

-- @Purpose: Cabecera de una orden de compra / refill.
--           Registra qué empleado compró, para qué sede y a qué proveedor.
CREATE TABLE Compras_Refill (
  id_compra INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empleado_refiller int NOT NULL,           -- Empleado que realizó la compra
  id_sede_destino int NOT NULL,                -- Sede que recibe el stock
  id_proveedor int NOT NULL,
  fecha_compra timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

-- @Purpose: Detalle de cada ítem comprado en una orden de refill.
--           Incluye el costo unitario pagado y el precio de venta sugerido.
CREATE TABLE Detalle_Compra_Refill (
  id_detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_compra int NOT NULL,
  id_item int NOT NULL,
  cantidad_comprada int NOT NULL CHECK (cantidad_comprada > 0),
  costo_unidad decimal(12, 2) NOT NULL CHECK (costo_unidad >= 0),
  precio_venta_sugerido decimal(12, 2) NOT NULL CHECK (precio_venta_sugerido >= 0)
);

-- ============================================================================
-- SECCIÓN 5: VENTAS
-- Transacciones de venta directa de productos al cliente final.
-- ============================================================================

-- @Purpose: Promociones y descuentos aplicables a ventas.
--           Pueden ser por categoría o por item específico (XOR), por día de
--           la semana o rango de fechas, con descuento porcentual o monto fijo.
CREATE TABLE Promociones (
  id_promocion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL,
  dia_semana int CHECK (
    dia_semana BETWEEN 1 AND 7                 -- 1=Lunes, 7=Domingo; NULL = aplica todos los días
  ),
  fecha_inicio date,                           -- NULL = sin fecha de inicio definida
  fecha_fin date,                              -- NULL = sin fecha de fin (indefinida)
  id_categoria_afectada int,                   -- XOR con id_item_afectado
  id_item_afectado int,                        -- XOR con id_categoria_afectada
  valor_descuento decimal(12, 2) NOT NULL CHECK (valor_descuento >= 0),
  tipo_descuento varchar(20) NOT NULL CHECK (tipo_descuento IN ('porcentaje', 'monto_fijo')),
  estado varchar(20) NOT NULL DEFAULT 'activa' CHECK (
    estado IN ('activa', 'pausada', 'vencida', 'cancelada')
  ),
  updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_promo_exactamente_uno CHECK (  -- Debe aplicar a categoría O a item, no ambos ni ninguno
    (
      id_categoria_afectada IS NOT NULL
      AND id_item_afectado IS NULL
    )
    OR (
      id_categoria_afectada IS NULL
      AND id_item_afectado IS NOT NULL
    )
  ),
  CONSTRAINT chk_porcentaje_promo CHECK (
    tipo_descuento != 'porcentaje'
    OR valor_descuento <= 100                  -- Descuento porcentual máximo 100%
  ),
  CONSTRAINT chk_fechas_promo CHECK (
    fecha_fin IS NULL
    OR fecha_fin > fecha_inicio                -- La fecha fin debe ser posterior al inicio
  )
);

-- @Purpose: Cabecera de una venta. Registra cliente (opcional), empleado
--           vendedor, sede y descuentos aplicados a nivel de venta.
CREATE TABLE Ventas (
  id_venta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_emision timestamptz NOT NULL DEFAULT now(),
  id_cliente int,                              -- NULL para venta anónima / consumidor final
  id_empleado int NOT NULL,                    -- Empleado que realizó la venta
  id_sede int NOT NULL,                        -- Sede donde se realizó la venta
  monto_descuento decimal(12, 2) NOT NULL DEFAULT 0 CHECK (monto_descuento >= 0),
  tipo_descuento varchar(20) CHECK (tipo_descuento IN ('porcentaje','monto_fijo')),
  justificacion_descuento text,                -- Razón del descuento (obligatorio si monto_descuento > 0)
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- @Purpose: Detalle de cada producto vendido en una venta.
--           Guarda el precio y costo al momento de la venta (snapshot histórico)
--           para que cambios futuros en Items no alteren registros pasados.
CREATE TABLE Detalle_Venta (
  id_detalle_v INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta int NOT NULL,
  id_item int NOT NULL,
  cantidad int NOT NULL CHECK (cantidad > 0),
  precio_unitario_momento decimal(12, 2) NOT NULL CHECK (precio_unitario_momento >= 0),  -- Snapshot del precio al vender
  costo_unitario_momento decimal(12, 2) NOT NULL CHECK (costo_unitario_momento >= 0),    -- Snapshot del costo al vender
  importe decimal(12, 2) NOT NULL CHECK (importe >= 0),                                   -- precio_unitario_momento * cantidad
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_det_venta_item UNIQUE (id_venta, id_item)  -- No se puede vender el mismo item dos veces en una venta
);

-- ============================================================================
-- SECCIÓN 6: REPARACIONES
-- Gestión del servicio técnico: ingreso de equipos, diagnóstico, reparación,
-- uso de repuestos y entrega al cliente.
-- ============================================================================

-- @Purpose: Orden de reparación de un equipo. Cubre todo el ciclo de vida:
--           ingreso → diagnóstico → reparación → terminado → entrega.
--           Incluye checklist de estado inicial, diagnóstico, fotos y montos.
CREATE TABLE Reparaciones (
  id_reparacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_ingreso timestamptz NOT NULL DEFAULT now(),
  id_cliente int NOT NULL,                     -- Dueño del equipo
  id_tecnico int NOT NULL,                     -- Técnico asignado (FK a Empleados)
  id_sede int NOT NULL,                        -- Sede donde se recibe el equipo
  marca varchar(50),                           -- Marca del equipo (ej: Samsung)
  modelo varchar(50),                          -- Modelo del equipo (ej: Galaxy A54)
  imei varchar(15) CHECK (imei ~ '^[0-9]{15}$'),  -- IMEI exacto de 15 dígitos
  esta_encendido boolean,                      -- TRUE si el equipo enciende al recibir
  checklist_estado jsonb,                      -- Checklist inicial en JSON (ej: {"pantalla":"rota","tactil":"funciona"})
  diagnostico_tecnico text,                    -- Diagnóstico detallado del técnico
  id_estado int NOT NULL,                      -- FK a Estados_Reparacion (estado actual)
  fecha_terminado timestamptz,                 -- Fecha en que se completó la reparación
  fecha_entrega_cliente timestamptz,           -- Fecha en que el cliente recogió el equipo
  monto_cotizado decimal(12, 2) CHECK (
    monto_cotizado IS NULL
    OR monto_cotizado >= 0                     -- Cotización aprobada (NULL = pendiente)
  ),
  monto_descuento decimal(12, 2) NOT NULL DEFAULT 0 CHECK (monto_descuento >= 0),
  tipo_descuento varchar(20) CHECK (tipo_descuento IN ('porcentaje','monto_fijo')),
  justificacion_descuento text,
  fotos jsonb,                                 -- Array de URLs o paths de fotos del equipo
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT chk_fechas_rep CHECK (             -- Validación de secuencia temporal lógica
    (
      fecha_terminado IS NULL
      OR fecha_terminado >= fecha_ingreso       -- No se puede terminar antes de ingresar
    )
    AND (
      fecha_entrega_cliente IS NULL
      OR (
        fecha_terminado IS NOT NULL
        AND fecha_entrega_cliente >= fecha_terminado  -- No se puede entregar antes de terminar
      )
    )
  )
);

-- @Purpose: Repuestos consumidos en una reparación. Cada fila asocia un item
--           (tipo='repuesto') con la cantidad usada, precio cobrado al cliente
--           y costo al momento del consumo (snapshot).
CREATE TABLE Reparacion_Repuestos_Usados (
  id_repuesto_u INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_reparacion int NOT NULL,
  id_item int NOT NULL,                        -- Debe ser item de tipo 'repuesto'
  cantidad int NOT NULL CHECK (cantidad > 0),
  precio_cobrado decimal(12, 2) NOT NULL CHECK (precio_cobrado >= 0),       -- Lo que se cobra al cliente por este repuesto
  costo_unitario_momento decimal(12, 2) NOT NULL CHECK (costo_unitario_momento >= 0)  -- Snapshot del costo
);

-- ============================================================================
-- SECCIÓN 7: DOCUMENTOS TRANSVERSALES
-- Entidades que aplican tanto a ventas como a reparaciones: garantías, pagos
-- y boletas de venta. Usan XOR (id_venta O id_reparacion, no ambos).
-- ============================================================================

-- @Purpose: Garantías emitidas por venta de producto o por servicio de
--           reparación. Solo una por transacción (XOR).
CREATE TABLE Garantias (
  id_garantia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta int,                                -- XOR: o venta o reparación
  id_reparacion int,                           -- XOR: o venta o reparación
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  estado varchar(20) NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa', 'vencida', 'invalidada')),
  motivo_invalidacion text,                    -- Razón si estado = 'invalidada'
  updated_at timestamptz DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_garantia_xor CHECK (
    (
      id_venta IS NOT NULL
      AND id_reparacion IS NULL                -- Garantía asociada a una venta
    )
    OR (
      id_venta IS NULL
      AND id_reparacion IS NOT NULL            -- Garantía asociada a una reparación
    )
  ),
  CONSTRAINT chk_fechas_garantia CHECK (fecha_fin > fecha_inicio)
);

-- @Purpose: Pagos registrados para ventas o reparaciones.
--           Soporta múltiples métodos de pago (efectivo, tarjeta, yape, plin, etc.).
--           Para reparaciones permite registrar adelantos (es_adelanto = true).
CREATE TABLE Pagos (
  id_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta int,                                -- XOR con id_reparacion
  id_reparacion int,                           -- XOR con id_venta
  metodo_pago varchar(30) NOT NULL CHECK (
    metodo_pago IN (
      'efectivo',
      'tarjeta',
      'transferencia',
      'yape',
      'plin',
      'otro'
    )
  ),
  monto decimal(12, 2) NOT NULL CHECK (monto > 0),
  es_adelanto boolean NOT NULL DEFAULT false,  -- TRUE si es pago parcial antes de completar (solo reparaciones)
  fecha_pago timestamptz NOT NULL DEFAULT now(),
  referencia_transaccion varchar(100),         -- Nro de operación, voucher, etc.
  CONSTRAINT chk_pago_xor CHECK (
    (
      id_venta IS NOT NULL
      AND id_reparacion IS NULL
    )
    OR (
      id_venta IS NULL
      AND id_reparacion IS NOT NULL
    )
  ),
  CONSTRAINT chk_adelanto_solo_reparacion CHECK (
    es_adelanto = false
    OR id_reparacion IS NOT NULL               -- Solo se permiten adelantos en reparaciones
  )
);

-- @Purpose: Boletas de venta electrónicas emitidas al cliente.
--           Aplica a ventas o reparaciones (XOR). Incluye cálculo de IGV.
CREATE TABLE Boletas (
  id_boleta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero varchar(20) NOT NULL UNIQUE,          -- Número de serie + correlativo
  fecha_emision timestamptz NOT NULL DEFAULT now(),
  id_venta int,                                -- XOR con id_reparacion
  id_reparacion int,                           -- XOR con id_venta
  subtotal decimal(12, 2) NOT NULL CHECK (subtotal >= 0),
  igv decimal(12, 2) NOT NULL DEFAULT 0 CHECK (igv >= 0),
  total decimal(12, 2) NOT NULL CHECK (total >= 0),
  estado varchar(20) NOT NULL DEFAULT 'emitida' CHECK (estado IN ('emitida', 'anulada')),
  CONSTRAINT chk_boleta_xor CHECK (
    (
      id_venta IS NOT NULL
      AND id_reparacion IS NULL
    )
    OR (
      id_venta IS NULL
      AND id_reparacion IS NOT NULL
    )
  ),
  CONSTRAINT chk_boleta_total CHECK (total = subtotal + igv)  -- Integridad contable: total = subtotal + IGV
);

-- ============================================================================
-- SECCIÓN 8: AUDITORÍA
-- Registro de acciones del sistema para trazabilidad y seguridad.
-- ============================================================================

-- @Purpose: Log centralizado de auditoría. Registra quién, cuándo, dónde y
--           qué acción se realizó sobre qué tabla, con referencia al registro
--           afectado y detalle de los cambios (útil para diffs).
CREATE TABLE Logs_Sistema (
  id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_hora timestamptz NOT NULL DEFAULT now(),
  id_empleado int,                             -- Empleado que ejecutó la acción (NULL para sistema)
  id_sede int,                                 -- Sede desde donde se ejecutó
  tipo_accion varchar(20) NOT NULL CHECK (
    tipo_accion IN (
      'creacion',
      'actualizacion',
      'eliminacion',
      'cambio_estado',
      'cambio_precio',
      'login',
      'logout',
      'error',
      'anulacion'
    )
  ),
  tabla_afectada varchar(100) NOT NULL CHECK (  -- Whitelist de tablas auditables
    tabla_afectada IN (
      'Sedes',
      'Empleados',
      'Clientes',
      'Items',
      'Inventario_Sedes',
      'Ventas',
      'Detalle_Venta',
      'Reparaciones',
      'Reparacion_Repuestos_Usados',
      'Compras_Refill',
      'Detalle_Compra_Refill',
      'Promociones',
      'Garantias',
      'Pagos',
      'Boletas',
      'Roles',
      'Empleado_Roles',
      'Marcas',
      'Categorias',
      'Proveedores',
      'Estados_Reparacion'
    )
  ),
  tipo_referencia varchar(30) CHECK (           -- Tipo de entidad referenciada
    tipo_referencia IN (
      'venta',
      'compra',
      'reparacion',
      'ajuste',
      'promocion',
      'otro'
    )
  ),
  id_referencia int,                            -- ID del registro afectado
  detalle_cambio text                           -- Descripción del cambio (ej: JSON diff)
);

-- ============================================================================
-- SECCIÓN 9: RELACIONES (FOREIGN KEYS)
-- Definidas con ALTER TABLE para control explícito del orden de creación.
-- Agrupadas por tabla destino para facilitar lectura y mantenimiento.
-- ============================================================================

-- === FK: Empleados ===
ALTER TABLE Empleados
ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);

-- === FK: Empleado_Roles ===
ALTER TABLE Empleado_Roles
ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado) ON DELETE CASCADE;
ALTER TABLE Empleado_Roles
ADD FOREIGN KEY (id_rol) REFERENCES Roles (id_rol) ON DELETE CASCADE;

-- === FK: Items ===
ALTER TABLE Items
ADD FOREIGN KEY (id_marca) REFERENCES Marcas (id_marca);
ALTER TABLE Items
ADD FOREIGN KEY (id_categoria) REFERENCES Categorias (id_categoria);

-- === FK: Inventario_Sedes ===
ALTER TABLE Inventario_Sedes
ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);
ALTER TABLE Inventario_Sedes
ADD FOREIGN KEY (id_item) REFERENCES Items (id_item);

-- === FK: Movimientos_Inventario ===
ALTER TABLE Movimientos_Inventario
ADD FOREIGN KEY (id_inventario) REFERENCES Inventario_Sedes (id_inventario);
ALTER TABLE Movimientos_Inventario
ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado);

-- === FK: Compras_Refill ===
ALTER TABLE Compras_Refill
ADD FOREIGN KEY (id_empleado_refiller) REFERENCES Empleados (id_empleado);
ALTER TABLE Compras_Refill
ADD FOREIGN KEY (id_sede_destino) REFERENCES Sedes (id_sede);
ALTER TABLE Compras_Refill
ADD FOREIGN KEY (id_proveedor) REFERENCES Proveedores (id_proveedor);

-- === FK: Detalle_Compra_Refill ===
ALTER TABLE Detalle_Compra_Refill
ADD FOREIGN KEY (id_compra) REFERENCES Compras_Refill (id_compra) ON DELETE CASCADE;
ALTER TABLE Detalle_Compra_Refill
ADD FOREIGN KEY (id_item) REFERENCES Items (id_item);

-- === FK: Promociones ===
ALTER TABLE Promociones
ADD FOREIGN KEY (id_categoria_afectada) REFERENCES Categorias (id_categoria);
ALTER TABLE Promociones
ADD FOREIGN KEY (id_item_afectado) REFERENCES Items (id_item);

-- === FK: Ventas ===
-- Razonamiento: ON DELETE SET NULL en id_cliente para preservar la venta si el cliente es eliminado.
ALTER TABLE Ventas
ADD FOREIGN KEY (id_cliente) REFERENCES Clientes (id_cliente) ON DELETE
SET NULL;
ALTER TABLE Ventas
ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado);
ALTER TABLE Ventas
ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);

-- === FK: Detalle_Venta ===
ALTER TABLE Detalle_Venta
ADD FOREIGN KEY (id_venta) REFERENCES Ventas (id_venta) ON DELETE CASCADE;
ALTER TABLE Detalle_Venta
ADD FOREIGN KEY (id_item) REFERENCES Items (id_item);

-- === FK: Reparaciones ===
ALTER TABLE Reparaciones
ADD FOREIGN KEY (id_estado) REFERENCES Estados_Reparacion (id_estado);
ALTER TABLE Reparaciones
ADD FOREIGN KEY (id_cliente) REFERENCES Clientes (id_cliente);
ALTER TABLE Reparaciones
ADD FOREIGN KEY (id_tecnico) REFERENCES Empleados (id_empleado);
ALTER TABLE Reparaciones
ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);

-- === FK: Reparacion_Repuestos_Usados ===
ALTER TABLE Reparacion_Repuestos_Usados
ADD FOREIGN KEY (id_reparacion) REFERENCES Reparaciones (id_reparacion) ON DELETE CASCADE;
ALTER TABLE Reparacion_Repuestos_Usados
ADD FOREIGN KEY (id_item) REFERENCES Items (id_item);

-- === FK: Garantias ===
ALTER TABLE Garantias
ADD FOREIGN KEY (id_venta) REFERENCES Ventas (id_venta) ON DELETE CASCADE;
ALTER TABLE Garantias
ADD FOREIGN KEY (id_reparacion) REFERENCES Reparaciones (id_reparacion) ON DELETE CASCADE;

-- === FK: Pagos ===
ALTER TABLE Pagos
ADD FOREIGN KEY (id_venta) REFERENCES Ventas (id_venta) ON DELETE CASCADE;
ALTER TABLE Pagos
ADD FOREIGN KEY (id_reparacion) REFERENCES Reparaciones (id_reparacion) ON DELETE CASCADE;

-- === FK: Boletas ===
ALTER TABLE Boletas
ADD FOREIGN KEY (id_venta) REFERENCES Ventas (id_venta) ON DELETE CASCADE;
ALTER TABLE Boletas
ADD FOREIGN KEY (id_reparacion) REFERENCES Reparaciones (id_reparacion) ON DELETE CASCADE;

-- === FK: Logs_Sistema ===
ALTER TABLE Logs_Sistema
ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado);
ALTER TABLE Logs_Sistema
ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);

-- ============================================================================
-- SECCIÓN 10: ÍNDICES
-- Optimizaciones para consultas frecuentes (filtros, joins, búsquedas).
-- Agrupados por tabla destino con comentario de propósito.
-- ============================================================================

-- === Índices: Ventas ===
-- Consultas frecuentes: filtrar ventas por sede + rango de fechas (reportes diarios).
CREATE INDEX idx_ventas_sede_fecha ON Ventas (id_sede, fecha_emision);
-- Joins desde otras tablas (boletas, pagos, garantías) hacia Ventas por cliente.
CREATE INDEX idx_ventas_cliente ON Ventas (id_cliente);

-- === Índices: Detalle_Venta ===
-- Join principal: obtener líneas de una venta específica.
CREATE INDEX idx_detalle_venta_venta ON Detalle_Venta (id_venta);
-- Consultas de producto más vendido / análisis de rotación por item.
CREATE INDEX idx_det_venta_item ON Detalle_Venta (id_item);

-- === Índices: Inventario_Sedes ===
-- Búsqueda de stock de un item específico en todas las sedes.
CREATE INDEX idx_inv_item ON Inventario_Sedes (id_item);

-- === Índices: Reparaciones ===
-- Reportes de reparaciones por sede + fecha de ingreso.
CREATE INDEX idx_reparaciones_sede_fecha ON Reparaciones (id_sede, fecha_ingreso);
-- Dashboard de reparaciones por estado (pendientes, en proceso, terminadas).
CREATE INDEX idx_reparaciones_estado ON Reparaciones (id_estado);
-- Historial de reparaciones por cliente.
CREATE INDEX idx_reparaciones_cliente ON Reparaciones (id_cliente);
-- Carga de trabajo por técnico.
CREATE INDEX idx_reparaciones_tecnico ON Reparaciones (id_tecnico);

-- === Índices: Reparacion_Repuestos_Usados ===
-- Análisis de repuestos más usados en reparaciones.
CREATE INDEX idx_rep_rep_usados_item ON Reparacion_Repuestos_Usados (id_item);

-- === Índices: Logs_Sistema ===
-- Consultas de auditoría por rango de fechas.
CREATE INDEX idx_logs_fecha_hora ON Logs_Sistema (fecha_hora);
-- Trazabilidad: buscar todos los logs de una entidad específica (ej: logs de la venta #123).
CREATE INDEX idx_logs_ref ON Logs_Sistema (tipo_referencia, id_referencia);

-- === Índices: Movimientos_Inventario ===
-- Auditoría de movimientos por fecha.
CREATE INDEX idx_mov_inv_fecha ON Movimientos_Inventario (fecha_movimiento);
-- Trazabilidad de stock: historial de movimientos de un registro de inventario específico.
CREATE INDEX idx_mov_inv_inventario ON Movimientos_Inventario (id_inventario, fecha_movimiento);

-- === Índices: Items ===
-- Búsqueda por modelo dentro del JSON de especificaciones (ej: "todos los items para iPhone 14").
CREATE INDEX idx_item_espec_modelo ON Items ((especificaciones->>'modelo'));

-- === Índices: Detalle_Compra_Refill ===
-- Análisis de compras por item (costo histórico, proveedores).
CREATE INDEX idx_det_compra_item ON Detalle_Compra_Refill (id_item);

-- === Índices: Pagos (parciales, solo filas con FK no nula) ===
-- Pagos asociados a una venta específica.
CREATE INDEX idx_pagos_venta ON Pagos (id_venta)
WHERE id_venta IS NOT NULL;
-- Pagos asociados a una reparación específica (incluye adelantos).
CREATE INDEX idx_pagos_reparacion ON Pagos (id_reparacion)
WHERE id_reparacion IS NOT NULL;

-- === Índices: Garantias (parciales, solo filas con FK no nula) ===
-- Garantías de una venta específica.
CREATE INDEX idx_garantias_venta ON Garantias (id_venta)
WHERE id_venta IS NOT NULL;
-- Garantías de una reparación específica.
CREATE INDEX idx_garantias_reparacion ON Garantias (id_reparacion)
WHERE id_reparacion IS NOT NULL;

-- === Índices: Boletas (parciales, solo filas con FK no nula) ===
-- Boletas emitidas para una venta.
CREATE INDEX idx_boletas_venta ON Boletas (id_venta)
WHERE id_venta IS NOT NULL;
-- Boletas emitidas para una reparación.
CREATE INDEX idx_boletas_reparacion ON Boletas (id_reparacion)
WHERE id_reparacion IS NOT NULL;