SET timezone = 'America/Lima';

-- ============================================================
-- SECCIÓN 1: CATÁLOGO / TABLAS BASE (sin FK entre sí)
-- ============================================================

-- Sedes físicas del negocio (tiendas/talleres)
CREATE TABLE Sedes (
  id_sede INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL,
  direccion text,
  telefono varchar(20),
  hora_apertura time,
  hora_cierre time,
  updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_horario_sede CHECK (hora_cierre != hora_apertura)
);

-- Roles laborales (técnico, vendedor, admin, etc.)
CREATE TABLE Roles (
  id_rol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_rol varchar(80) NOT NULL UNIQUE
);

-- Marcas de productos/repuestos
CREATE TABLE Marcas (
  id_marca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL UNIQUE
);

-- Categorías de productos (solo aplica a tipo='producto')
CREATE TABLE Categorias (
  id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_categoria varchar(100) NOT NULL UNIQUE
);

-- Estados del flujo de reparación (orden secuencial, es_final cierra el proceso)
CREATE TABLE Estados_Reparacion (
  id_estado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(30) NOT NULL UNIQUE,
  descripcion text,
  orden int NOT NULL,
  es_final boolean NOT NULL DEFAULT false
);

-- Proveedores para compras de refill
CREATE TABLE Proveedores (
  id_proveedor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ruc varchar(15) NOT NULL UNIQUE,
  razon_social varchar(200) NOT NULL,
  contacto_nombre varchar(100),
  telefono varchar(20),
  updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- SECCIÓN 2: PERSONAS
-- ============================================================

-- Empleados. Pertenece a una sede, puede tener múltiples roles (Empleado_Roles)
CREATE TABLE Empleados (
  id_empleado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sede int NOT NULL,
  tipo_documento varchar(20) NOT NULL,
  nro_documento varchar(30) NOT NULL,
  nombre_completo varchar(150) NOT NULL,
  telefono varchar(20),
  sueldo_semanal_soles decimal(10, 2) NOT NULL CHECK (sueldo_semanal_soles >= 0),
  estado varchar(20) NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo', 'suspendido')),
  es_extranjero boolean DEFAULT false,
  direccion_completa text,
  password_hash varchar(255) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz,
  CONSTRAINT uq_empleado_doc UNIQUE (tipo_documento, nro_documento)
);

-- Relación muchos-a-muchos Empleados ↔ Roles
CREATE TABLE Empleado_Roles (
  id_empleado int NOT NULL,
  id_rol int NOT NULL,
  PRIMARY KEY (id_empleado, id_rol)
);

-- Clientes (compradores y dueños de equipos en reparación)
CREATE TABLE Clientes (
  id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_documento varchar(20) NOT NULL,
  nro_documento varchar(30) NOT NULL,
  nombre_completo varchar(150) NOT NULL,
  telefono varchar(20),
  direccion_completa text,
  es_extranjero boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz,
  CONSTRAINT uq_cliente_doc UNIQUE (tipo_documento, nro_documento)
);

-- ============================================================
-- SECCIÓN 3: INVENTARIO Y PRODUCTOS
-- ============================================================

-- Catálogo unificado: 'producto' (venta directa, requiere categoría) o 'repuesto' (reparaciones, puede tener calidad)
CREATE TABLE Items (
  id_item INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar(15) NOT NULL CHECK (tipo IN ('producto', 'repuesto')),
  sku varchar(50) NOT NULL UNIQUE,
  nombre varchar(150) NOT NULL,
  id_marca int,
  id_categoria int,
  modelo varchar(100),
  calidad varchar(30),
  especificaciones jsonb,
  precio_compra_actual decimal(12, 2) NOT NULL CHECK (precio_compra_actual >= 0),
  precio_venta_actual decimal(12, 2) NOT NULL CHECK (precio_venta_actual >= 0),
  updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_precio_item CHECK (precio_venta_actual >= precio_compra_actual),
  CONSTRAINT chk_calidad_solo_repuesto CHECK (
    calidad IS NULL OR tipo = 'repuesto'
  ),
  CONSTRAINT chk_categoria_solo_producto CHECK (
    id_categoria IS NOT NULL OR tipo = 'repuesto'
  )
);

-- Stock por sede+item. stock_minimo dispara alertas de reabastecimiento
CREATE TABLE Inventario_Sedes (
  id_inventario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sede int NOT NULL,
  id_item int NOT NULL,
  cantidad_actual int NOT NULL CHECK (cantidad_actual >= 0),
  stock_minimo int NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
  CONSTRAINT uq_inventario_sede_item UNIQUE (id_sede, id_item)
);

-- Bitácora de movimientos de inventario (compras, ventas, ajustes, transferencias, consumo en reparaciones)
CREATE TABLE Movimientos_Inventario (
  id_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_inventario int NOT NULL,
  tipo_movimiento varchar(30) NOT NULL CHECK (
    tipo_movimiento IN ('compra','venta','ajuste_manual','ajuste_stock','transferencia_entrada','transferencia_salida','consumo_reparacion')
  ),
  id_empleado int NOT NULL,
  cantidad int NOT NULL CHECK (cantidad != 0),
  stock_antes int NOT NULL,
  stock_despues int NOT NULL,
  fecha_movimiento timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_mov_stock CHECK (stock_despues >= 0)
);

-- ============================================================
-- SECCIÓN 4: COMPRAS (REFILL)
-- ============================================================

-- Cabecera de compra a proveedor para reabastecer una sede
CREATE TABLE Compras_Refill (
  id_compra INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empleado_refiller int NOT NULL,
  id_sede_destino int NOT NULL,
  id_proveedor int NOT NULL,
  fecha_compra timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

-- Detalle de cada ítem comprado (costo pagado y precio de venta sugerido)
CREATE TABLE Detalle_Compra_Refill (
  id_detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_compra int NOT NULL,
  id_item int NOT NULL,
  cantidad_comprada int NOT NULL CHECK (cantidad_comprada > 0),
  costo_unidad decimal(12, 2) NOT NULL CHECK (costo_unidad >= 0),
  precio_venta_sugerido decimal(12, 2) NOT NULL CHECK (precio_venta_sugerido >= 0)
);

-- ============================================================
-- SECCIÓN 5: VENTAS
-- ============================================================

-- Promociones y descuentos. Aplica a categoría O a item (XOR). Por día de semana o rango de fechas
CREATE TABLE Promociones (
  id_promocion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL,
  dia_semana int CHECK (dia_semana BETWEEN 1 AND 7),
  fecha_inicio date,
  fecha_fin date,
  id_categoria_afectada int,
  id_item_afectado int,
  valor_descuento decimal(12, 2) NOT NULL CHECK (valor_descuento >= 0),
  tipo_descuento varchar(20) NOT NULL CHECK (tipo_descuento IN ('porcentaje', 'monto_fijo')),
  estado varchar(20) NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa', 'pausada', 'vencida', 'cancelada')),
  updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_promo_exactamente_uno CHECK (
    (id_categoria_afectada IS NOT NULL AND id_item_afectado IS NULL)
    OR (id_categoria_afectada IS NULL AND id_item_afectado IS NOT NULL)
  ),
  CONSTRAINT chk_porcentaje_promo CHECK (
    tipo_descuento != 'porcentaje' OR valor_descuento <= 100
  ),
  CONSTRAINT chk_fechas_promo CHECK (
    fecha_fin IS NULL OR fecha_fin > fecha_inicio
  )
);

-- Cabecera de venta. Cliente opcional (NULL = consumidor final)
CREATE TABLE Ventas (
  id_venta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_emision timestamptz NOT NULL DEFAULT now(),
  id_cliente int,
  id_empleado int NOT NULL,
  id_sede int NOT NULL,
  monto_descuento decimal(12, 2) NOT NULL DEFAULT 0 CHECK (monto_descuento >= 0),
  tipo_descuento varchar(20) CHECK (tipo_descuento IN ('porcentaje','monto_fijo')),
  justificacion_descuento text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Detalle de cada producto vendido. Snapshots de precio y costo al momento de venta
CREATE TABLE Detalle_Venta (
  id_detalle_v INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta int NOT NULL,
  id_item int NOT NULL,
  cantidad int NOT NULL CHECK (cantidad > 0),
  precio_unitario_momento decimal(12, 2) NOT NULL CHECK (precio_unitario_momento >= 0),
  costo_unitario_momento decimal(12, 2) NOT NULL CHECK (costo_unitario_momento >= 0),
  importe decimal(12, 2) NOT NULL CHECK (importe >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_det_venta_item UNIQUE (id_venta, id_item)
);

-- ============================================================
-- SECCIÓN 5.5: CAMBIOS DE PRODUCTO
-- ============================================================

-- Intercambio de producto vendido. Sin devolución monetaria: si el nuevo item
-- cuesta más, se cobra la diferencia
CREATE TABLE Cambios_Producto (
  id_cambio              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta_origen        int NOT NULL,
  id_garantia            int,
  id_empleado            int NOT NULL,
  id_sede                int NOT NULL,
  id_item_devuelto       int NOT NULL,
  cantidad               int NOT NULL CHECK (cantidad > 0),
  precio_devuelto        decimal(12,2) NOT NULL CHECK (precio_devuelto >= 0),
  id_item_entregado      int NOT NULL,
  precio_entregado       decimal(12,2) NOT NULL CHECK (precio_entregado >= 0),
  diferencia_cobrada     decimal(12,2) NOT NULL DEFAULT 0 CHECK (diferencia_cobrada >= 0),
  metodo_pago_dif        varchar(30) CHECK (metodo_pago_dif IN ('efectivo','tarjeta','transferencia','yape','plin','otro')),
  referencia_transaccion varchar(100),
  motivo                 varchar(50) NOT NULL CHECK (motivo IN ('defecto', 'garantia', 'otro')),
  detalle                text,
  fecha_cambio           timestamptz NOT NULL DEFAULT now(),
  created_at             timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_cambio_items_distintos CHECK (id_item_devuelto != id_item_entregado),
  CONSTRAINT chk_metodo_requerido CHECK (
    diferencia_cobrada = 0 OR metodo_pago_dif IS NOT NULL
  ),
  CONSTRAINT chk_diferencia_razonable CHECK (
    diferencia_cobrada <= GREATEST((precio_entregado - precio_devuelto) * cantidad, 0)
  )
);

-- ============================================================
-- SECCIÓN 6: REPARACIONES
-- ============================================================

-- Orden de reparación: ingreso → diagnóstico → reparación → terminado → entrega
CREATE TABLE Reparaciones (
  id_reparacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_ingreso timestamptz NOT NULL DEFAULT now(),
  id_cliente int NOT NULL,
  id_tecnico int NOT NULL,
  id_sede int NOT NULL,
  marca varchar(50),
  modelo varchar(50),
  imei varchar(15) CHECK (imei ~ '^[0-9]{15}$'),
  esta_encendido boolean,
  pantalla_rota boolean,
  mojado boolean,
  golpeado boolean,
  tiene_funda boolean,
  tiene_chip boolean,
  tiene_memoria boolean,
  observaciones_ingreso text,
  fotos_urls jsonb,
  diagnostico_tecnico text,
  monto_cotizado decimal(12, 2) CHECK (monto_cotizado >= 0),
  fecha_terminado timestamptz,
  fecha_entrega_cliente timestamptz,
  monto_descuento decimal(12, 2) NOT NULL DEFAULT 0 CHECK (monto_descuento >= 0),
  tipo_descuento varchar(20) CHECK (tipo_descuento IN ('porcentaje','monto_fijo')),
  justificacion_descuento text,
  id_estado int NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Repuestos usados en una reparación (snapshot de precio y costo al momento de uso)
CREATE TABLE Reparacion_Repuestos_Usados (
  id_reparacion_repuesto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_reparacion int NOT NULL,
  id_item int NOT NULL,
  cantidad int NOT NULL CHECK (cantidad > 0),
  precio_cobrado decimal(12, 2) NOT NULL CHECK (precio_cobrado >= 0),
  costo_unitario_momento decimal(12, 2) NOT NULL CHECK (costo_unitario_momento >= 0)
);

-- ============================================================
-- SECCIÓN 7: GARANTÍAS, PAGOS Y BOLETAS
-- ============================================================

-- Garantía asociada a una venta O a una reparación (XOR). Solo una por transacción
CREATE TABLE Garantias (
  id_garantia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta int,
  id_reparacion int,
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  estado varchar(20) NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa', 'vencida', 'invalidada')),
  motivo_invalidacion text,
  updated_at timestamptz DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_garantia_xor CHECK (
    (id_venta IS NOT NULL AND id_reparacion IS NULL)
    OR (id_venta IS NULL AND id_reparacion IS NOT NULL)
  ),
  CONSTRAINT chk_fechas_garantia CHECK (fecha_fin > fecha_inicio)
);

-- Pagos de ventas o reparaciones (XOR). es_adelanto solo para reparaciones
CREATE TABLE Pagos (
  id_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta int,
  id_reparacion int,
  metodo_pago varchar(30) NOT NULL CHECK (
    metodo_pago IN ('efectivo','tarjeta','transferencia','yape','plin','otro')
  ),
  monto decimal(12, 2) NOT NULL CHECK (monto > 0),
  es_adelanto boolean NOT NULL DEFAULT false,
  fecha_pago timestamptz NOT NULL DEFAULT now(),
  referencia_transaccion varchar(100),
  CONSTRAINT chk_pago_xor CHECK (
    (id_venta IS NOT NULL AND id_reparacion IS NULL)
    OR (id_venta IS NULL AND id_reparacion IS NOT NULL)
  ),
  CONSTRAINT chk_adelanto_solo_reparacion CHECK (
    es_adelanto = false OR id_reparacion IS NOT NULL
  )
);

-- Boletas electrónicas de venta o reparación (XOR)
CREATE TABLE Boletas (
  id_boleta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero varchar(20) NOT NULL UNIQUE,
  fecha_emision timestamptz NOT NULL DEFAULT now(),
  id_venta int,
  id_reparacion int,
  total decimal(12, 2) NOT NULL CHECK (total >= 0),
  estado varchar(20) NOT NULL DEFAULT 'emitida' CHECK (estado IN ('emitida', 'anulada')),
  url_pdf varchar(500),
  CONSTRAINT chk_boleta_xor CHECK (
    (id_venta IS NOT NULL AND id_reparacion IS NULL)
    OR (id_venta IS NULL AND id_reparacion IS NOT NULL)
  )
);

-- ============================================================
-- SECCIÓN 8: AUDITORÍA
-- ============================================================

-- Log centralizado: quién, cuándo, dónde, qué acción sobre qué tabla
CREATE TABLE Logs_Sistema (
  id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_hora timestamptz NOT NULL DEFAULT now(),
  id_empleado int,
  id_sede int,
  tipo_accion varchar(20) NOT NULL CHECK (
    tipo_accion IN ('creacion','actualizacion','eliminacion','cambio_estado','cambio_precio','login','logout','error','anulacion')
  ),
  tabla_afectada varchar(100) NOT NULL CHECK (
    tabla_afectada IN (
      'Sedes','Empleados','Clientes','Items','Inventario_Sedes','Ventas','Detalle_Venta',
      'Reparaciones','Reparacion_Repuestos_Usados','Compras_Refill','Detalle_Compra_Refill',
      'Promociones','Garantias','Pagos','Boletas','Roles','Empleado_Roles','Marcas',
      'Categorias','Proveedores','Estados_Reparacion','Cambios_Producto'
    )
  ),
  tipo_referencia varchar(30) CHECK (
    tipo_referencia IN ('venta','compra','reparacion','ajuste','promocion','cambio','otro')
  ),
  id_referencia int,
  detalle_cambio text
);

-- ============================================================
-- SECCIÓN 9: FOREIGN KEYS
-- ============================================================

-- FK: Empleados
ALTER TABLE Empleados ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);

-- FK: Empleado_Roles
ALTER TABLE Empleado_Roles ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado) ON DELETE CASCADE;
ALTER TABLE Empleado_Roles ADD FOREIGN KEY (id_rol) REFERENCES Roles (id_rol) ON DELETE CASCADE;

-- FK: Items
ALTER TABLE Items ADD FOREIGN KEY (id_marca) REFERENCES Marcas (id_marca);
ALTER TABLE Items ADD FOREIGN KEY (id_categoria) REFERENCES Categorias (id_categoria);

-- FK: Inventario_Sedes
ALTER TABLE Inventario_Sedes ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);
ALTER TABLE Inventario_Sedes ADD FOREIGN KEY (id_item) REFERENCES Items (id_item);

-- FK: Movimientos_Inventario
ALTER TABLE Movimientos_Inventario ADD FOREIGN KEY (id_inventario) REFERENCES Inventario_Sedes (id_inventario);
ALTER TABLE Movimientos_Inventario ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado);

-- FK: Compras_Refill
ALTER TABLE Compras_Refill ADD FOREIGN KEY (id_empleado_refiller) REFERENCES Empleados (id_empleado);
ALTER TABLE Compras_Refill ADD FOREIGN KEY (id_sede_destino) REFERENCES Sedes (id_sede);
ALTER TABLE Compras_Refill ADD FOREIGN KEY (id_proveedor) REFERENCES Proveedores (id_proveedor);

-- FK: Detalle_Compra_Refill
ALTER TABLE Detalle_Compra_Refill ADD FOREIGN KEY (id_compra) REFERENCES Compras_Refill (id_compra) ON DELETE CASCADE;
ALTER TABLE Detalle_Compra_Refill ADD FOREIGN KEY (id_item) REFERENCES Items (id_item);

-- FK: Promociones
ALTER TABLE Promociones ADD FOREIGN KEY (id_categoria_afectada) REFERENCES Categorias (id_categoria);
ALTER TABLE Promociones ADD FOREIGN KEY (id_item_afectado) REFERENCES Items (id_item);

-- FK: Ventas (ON DELETE SET NULL en id_cliente para preservar la venta)
ALTER TABLE Ventas ADD FOREIGN KEY (id_cliente) REFERENCES Clientes (id_cliente) ON DELETE SET NULL;
ALTER TABLE Ventas ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado);
ALTER TABLE Ventas ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);

-- FK: Detalle_Venta
ALTER TABLE Detalle_Venta ADD FOREIGN KEY (id_venta) REFERENCES Ventas (id_venta) ON DELETE CASCADE;
ALTER TABLE Detalle_Venta ADD FOREIGN KEY (id_item) REFERENCES Items (id_item);

-- FK: Reparaciones
ALTER TABLE Reparaciones ADD FOREIGN KEY (id_estado) REFERENCES Estados_Reparacion (id_estado);
ALTER TABLE Reparaciones ADD FOREIGN KEY (id_cliente) REFERENCES Clientes (id_cliente);
ALTER TABLE Reparaciones ADD FOREIGN KEY (id_tecnico) REFERENCES Empleados (id_empleado);
ALTER TABLE Reparaciones ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);

-- FK: Reparacion_Repuestos_Usados
ALTER TABLE Reparacion_Repuestos_Usados ADD FOREIGN KEY (id_reparacion) REFERENCES Reparaciones (id_reparacion) ON DELETE CASCADE;
ALTER TABLE Reparacion_Repuestos_Usados ADD FOREIGN KEY (id_item) REFERENCES Items (id_item);

-- FK: Garantias
ALTER TABLE Garantias ADD FOREIGN KEY (id_venta) REFERENCES Ventas (id_venta) ON DELETE CASCADE;
ALTER TABLE Garantias ADD FOREIGN KEY (id_reparacion) REFERENCES Reparaciones (id_reparacion) ON DELETE CASCADE;

-- FK: Cambios_Producto
ALTER TABLE Cambios_Producto ADD FOREIGN KEY (id_venta_origen) REFERENCES Ventas (id_venta);
ALTER TABLE Cambios_Producto ADD FOREIGN KEY (id_garantia) REFERENCES Garantias (id_garantia) ON DELETE SET NULL;
ALTER TABLE Cambios_Producto ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado);
ALTER TABLE Cambios_Producto ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);
ALTER TABLE Cambios_Producto ADD FOREIGN KEY (id_item_devuelto) REFERENCES Items (id_item);
ALTER TABLE Cambios_Producto ADD FOREIGN KEY (id_item_entregado) REFERENCES Items (id_item);

-- FK: Pagos
ALTER TABLE Pagos ADD FOREIGN KEY (id_venta) REFERENCES Ventas (id_venta) ON DELETE CASCADE;
ALTER TABLE Pagos ADD FOREIGN KEY (id_reparacion) REFERENCES Reparaciones (id_reparacion) ON DELETE CASCADE;

-- FK: Boletas
ALTER TABLE Boletas ADD FOREIGN KEY (id_venta) REFERENCES Ventas (id_venta) ON DELETE CASCADE;
ALTER TABLE Boletas ADD FOREIGN KEY (id_reparacion) REFERENCES Reparaciones (id_reparacion) ON DELETE CASCADE;

-- FK: Logs_Sistema
ALTER TABLE Logs_Sistema ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado);
ALTER TABLE Logs_Sistema ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);

-- ============================================================
-- SECCIÓN 10: ÍNDICES
-- ============================================================

-- Ventas: reportes por sede+fecha y joins por cliente
CREATE INDEX idx_ventas_sede_fecha ON Ventas (id_sede, fecha_emision);
CREATE INDEX idx_ventas_cliente ON Ventas (id_cliente);

-- Detalle_Venta: joins a venta y análisis de rotación por item
CREATE INDEX idx_detalle_venta_venta ON Detalle_Venta (id_venta);
CREATE INDEX idx_det_venta_item ON Detalle_Venta (id_item);

-- Inventario: búsqueda de stock por item
CREATE INDEX idx_inv_item ON Inventario_Sedes (id_item);

-- Reparaciones: reportes por sede+fecha, estado, cliente y técnico
CREATE INDEX idx_reparaciones_sede_fecha ON Reparaciones (id_sede, fecha_ingreso);
CREATE INDEX idx_reparaciones_estado ON Reparaciones (id_estado);
CREATE INDEX idx_reparaciones_cliente ON Reparaciones (id_cliente);
CREATE INDEX idx_reparaciones_tecnico ON Reparaciones (id_tecnico);

-- Reparacion_Repuestos_Usados: repuestos más usados
CREATE INDEX idx_rep_rep_usados_item ON Reparacion_Repuestos_Usados (id_item);

-- Logs: auditoría por fecha y trazabilidad por entidad
CREATE INDEX idx_logs_fecha_hora ON Logs_Sistema (fecha_hora);
CREATE INDEX idx_logs_ref ON Logs_Sistema (tipo_referencia, id_referencia);

-- Movimientos_Inventario: auditoría por fecha e historial por inventario
CREATE INDEX idx_mov_inv_fecha ON Movimientos_Inventario (fecha_movimiento);
CREATE INDEX idx_mov_inv_inventario ON Movimientos_Inventario (id_inventario, fecha_movimiento);

-- Items: búsqueda por modelo en JSON de especificaciones
CREATE INDEX idx_item_espec_modelo ON Items ((especificaciones->>'modelo'));

-- Detalle_Compra_Refill: análisis de compras por item
CREATE INDEX idx_det_compra_item ON Detalle_Compra_Refill (id_item);

-- Pagos (índices parciales, solo filas con FK no nula)
CREATE INDEX idx_pagos_venta ON Pagos (id_venta) WHERE id_venta IS NOT NULL;
CREATE INDEX idx_pagos_reparacion ON Pagos (id_reparacion) WHERE id_reparacion IS NOT NULL;

-- Garantias (índices parciales, solo filas con FK no nula)
CREATE INDEX idx_garantias_venta ON Garantias (id_venta) WHERE id_venta IS NOT NULL;
CREATE INDEX idx_garantias_reparacion ON Garantias (id_reparacion) WHERE id_reparacion IS NOT NULL;

-- Boletas (índices parciales, solo filas con FK no nula)
CREATE INDEX idx_boletas_venta ON Boletas (id_venta) WHERE id_venta IS NOT NULL;
CREATE INDEX idx_boletas_reparacion ON Boletas (id_reparacion) WHERE id_reparacion IS NOT NULL;

-- Cambios_Producto: trazabilidad, reportes y análisis
CREATE INDEX idx_cambios_venta_origen ON Cambios_Producto (id_venta_origen);
CREATE INDEX idx_cambios_sede_fecha ON Cambios_Producto (id_sede, fecha_cambio);
CREATE INDEX idx_cambios_item_devuelto ON Cambios_Producto (id_item_devuelto);
CREATE INDEX idx_cambios_item_entregado ON Cambios_Producto (id_item_entregado);