-- PRIMERA PARTE

SET timezone = 'America/Lima';

CREATE TABLE Sedes (
  id_sede INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL,
  direccion text,
  telefono varchar(20),
  hora_apertura time,
  hora_cierre time,
  -- Permite deshabilitar una sede sin eliminarla; los triggers bloquean operaciones
  -- (ventas, reparaciones, compras) sobre sedes con esta_habilitada = false.
  esta_habilitada boolean NOT NULL DEFAULT true,
  -- Empleado (Propietario) que creó el registro; NULL en datos de seed o migración inicial.
  created_by int,
  updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_horario_sede CHECK (hora_cierre != hora_apertura)
);

CREATE TABLE Roles (
  id_rol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_rol varchar(80) NOT NULL UNIQUE
);

CREATE TABLE Marcas (
  id_marca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL UNIQUE
);

CREATE TABLE Categorias (
  id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_categoria varchar(100) NOT NULL UNIQUE
);

CREATE TABLE Estados_Reparacion (
  id_estado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(30) NOT NULL UNIQUE,
  descripcion text,
  orden int NOT NULL,
  es_final boolean NOT NULL DEFAULT false
);

CREATE TABLE Proveedores (
  id_proveedor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ruc varchar(15) NOT NULL UNIQUE,
  razon_social varchar(200) NOT NULL,
  contacto_nombre varchar(100),
  telefono varchar(20),
  updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- SEGUNDA PARTE

CREATE TABLE Empleados (
  id_empleado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sede int,
  tipo_documento varchar(20) NOT NULL,
  nro_documento varchar(30) NOT NULL,
  nombre_completo varchar(150) NOT NULL,
  telefono varchar(20),
  sueldo_semanal_soles decimal(10, 2) NOT NULL CHECK (sueldo_semanal_soles >= 0),
  estado varchar(20) NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo', 'suspendido')),
  es_extranjero boolean DEFAULT false,
  direccion_completa text,
  password_hash varchar(255) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz,
  -- Empleado (Propietario o Gerente) que dio de alta este registro; NULL en datos de seed.
  created_by int,
  id_rol INT NOT NULL REFERENCES Roles(id_rol),
  CONSTRAINT uq_empleado_doc UNIQUE (tipo_documento, nro_documento),
  CONSTRAINT chk_nro_doc_len_empleado CHECK (
    (tipo_documento = 'DNI'       AND char_length(nro_documento) = 8)
    OR (tipo_documento = 'CE'        AND char_length(nro_documento) = 12)
    OR (tipo_documento = 'pasaporte' AND char_length(nro_documento) = 9)
  )
);

CREATE TABLE Clientes (
  id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_documento varchar(20) NOT NULL,
  nro_documento varchar(30) NOT NULL,
  nombre_completo varchar(150) NOT NULL,
  telefono varchar(20),
  direccion_completa text,
  es_extranjero boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz,
  CONSTRAINT uq_cliente_doc UNIQUE (tipo_documento, nro_documento),
  CONSTRAINT chk_nro_doc_len_cliente CHECK (
    (tipo_documento = 'DNI'       AND char_length(nro_documento) = 8)
    OR (tipo_documento = 'CE'        AND char_length(nro_documento) = 12)
    OR (tipo_documento = 'pasaporte' AND char_length(nro_documento) = 9)
  )
);

-- TERCERA PARTE

CREATE TABLE Items (
  id_item INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar(15) NOT NULL CHECK (tipo IN ('producto', 'repuesto')),
  sku varchar(50) NOT NULL UNIQUE,
  nombre varchar(150) NOT NULL,
  id_marca int,
  modelo varchar(100),
  calidad varchar(30),
  especificaciones jsonb,
  precio_compra_actual decimal(12, 2) NOT NULL CHECK (precio_compra_actual >= 0),
  precio_venta_actual decimal(12, 2) NOT NULL CHECK (precio_venta_actual >= 0),
  updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_precio_item CHECK (precio_venta_actual >= precio_compra_actual),
  CONSTRAINT chk_calidad_solo_repuesto CHECK (
    calidad IS NULL
    OR tipo = 'repuesto'
  )
);

CREATE TABLE Item_Categorias (
  id_item      INT NOT NULL REFERENCES Items(id_item) ON DELETE CASCADE,
  id_categoria INT NOT NULL REFERENCES Categorias(id_categoria) ON DELETE RESTRICT,
  PRIMARY KEY (id_item, id_categoria)
);

CREATE INDEX idx_item_categorias_item      ON Item_Categorias(id_item);
CREATE INDEX idx_item_categorias_categoria ON Item_Categorias(id_categoria);

CREATE TABLE Inventario_Sedes (
  id_inventario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sede int NOT NULL,
  id_item int NOT NULL,
  cantidad_actual int NOT NULL CHECK (cantidad_actual >= 0),
  stock_minimo int NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
  CONSTRAINT uq_inventario_sede_item UNIQUE (id_sede, id_item)
);

CREATE TABLE Movimientos_Inventario (
  id_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_inventario int NOT NULL,
  tipo_movimiento varchar(30) NOT NULL CHECK (
    tipo_movimiento IN (
      'compra',
      'venta',
      'ajuste_manual',
      'transferencia',
      'reparacion',
      'cambio'
    )
  ),
  cantidad int NOT NULL,
  id_referencia int,
  id_empleado int,
  fecha_movimiento timestamptz NOT NULL DEFAULT now()
);

-- CUARTA PARTE

CREATE TABLE Compras_Refill (
  id_compra INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empleado_refiller int NOT NULL,
  id_sede_destino int NOT NULL,
  id_proveedor int NOT NULL,
  fecha_compra timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

CREATE TABLE Detalle_Compra_Refill (
  id_detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_compra int NOT NULL,
  id_item int NOT NULL,
  cantidad_comprada int NOT NULL CHECK (cantidad_comprada > 0),
  costo_unidad decimal(12, 2) NOT NULL CHECK (costo_unidad >= 0),
  precio_venta_sugerido decimal(12, 2) NOT NULL CHECK (precio_venta_sugerido >= 0)
);

-- QUINTA PARTE

CREATE TABLE Promociones (
  id_promocion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL,
  dia_semana int CHECK (
    dia_semana BETWEEN 1 AND 7
  ),
  fecha_inicio date,
  fecha_fin date,
  id_categoria_afectada int,
  id_item_afectado int,
  valor_descuento decimal(12, 2) NOT NULL CHECK (valor_descuento >= 0),
  tipo_descuento varchar(20) NOT NULL CHECK (tipo_descuento IN ('porcentaje', 'monto_fijo')),
  estado varchar(20) NOT NULL DEFAULT 'activa' CHECK (
    estado IN ('activa', 'pausada', 'vencida', 'cancelada')
  ),
  updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_promo_exactamente_uno CHECK (
    (
      id_categoria_afectada IS NOT NULL
      AND id_item_afectado IS NULL
    )
    OR (
      id_categoria_afectada IS NULL
      AND id_item_afectado IS NOT NULL
    )
  ),
  CONSTRAINT chk_porcentaje_promo CHECK (
    tipo_descuento != 'porcentaje'
    OR valor_descuento <= 100
  ),
  CONSTRAINT chk_fechas_promo CHECK (
    fecha_fin IS NULL
    OR fecha_fin > fecha_inicio
  )
);

CREATE TABLE Ventas (
  id_venta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_emision timestamptz NOT NULL DEFAULT now(),
  id_cliente int,
  id_empleado int NOT NULL,
  id_sede int NOT NULL,
  monto_descuento decimal(12, 2) NOT NULL DEFAULT 0 CHECK (monto_descuento >= 0),
  tipo_descuento varchar(20) CHECK (tipo_descuento IN ('porcentaje','monto_fijo')),
  justificacion_descuento text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE Detalle_Venta (
  id_detalle_v INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta int NOT NULL,
  id_item int NOT NULL,
  cantidad int NOT NULL CHECK (cantidad > 0),
  precio_unitario_momento decimal(12, 2) NOT NULL CHECK (precio_unitario_momento >= 0),
  precio_normal_momento decimal(12, 2) NULL CHECK (precio_normal_momento >= 0),
  costo_unitario_momento decimal(12, 2) NOT NULL CHECK (costo_unitario_momento >= 0),
  importe decimal(12, 2) NOT NULL CHECK (importe >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_det_venta_item UNIQUE (id_venta, id_item)
);

-- QUINTA PARTE (bis)

CREATE TABLE Cambios_Producto (
  id_cambio              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta_origen        int NOT NULL,
  id_garantia            int,
  id_empleado            int NOT NULL,
  id_sede                int NOT NULL,
  id_item_devuelto       int NOT NULL,
  cantidad               int NOT NULL CHECK (cantidad > 0),
  precio_devuelto        decimal(12,2) NOT NULL CHECK (precio_devuelto >= 0),
  id_item_entregado      int NOT NULL,
  precio_entregado       decimal(12,2) NOT NULL CHECK (precio_entregado >= 0),
  diferencia_cobrada     decimal(12,2) NOT NULL DEFAULT 0 CHECK (diferencia_cobrada >= 0),
  metodo_pago_dif        varchar(30) CHECK (metodo_pago_dif IN ('efectivo','tarjeta','transferencia','yape','plin','otro')),
  referencia_transaccion varchar(100),
  motivo                 varchar(50) NOT NULL CHECK (motivo IN ('defecto', 'garantia', 'otro')),
  detalle                text,
  fecha_cambio           timestamptz NOT NULL DEFAULT now(),
  created_at             timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_cambio_items_distintos CHECK (id_item_devuelto != id_item_entregado),
  CONSTRAINT chk_metodo_requerido CHECK (
    diferencia_cobrada = 0 OR metodo_pago_dif IS NOT NULL
  ),
  CONSTRAINT chk_diferencia_razonable CHECK (
    diferencia_cobrada <= GREATEST((precio_entregado - precio_devuelto) * cantidad, 0)
  )
);

-- SEXTA PARTE

CREATE TABLE Reparaciones (
  id_reparacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_ingreso timestamptz NOT NULL DEFAULT now(),
  id_cliente int NOT NULL,
  id_tecnico int NOT NULL,
  id_sede int NOT NULL,
  marca varchar(50),
  modelo varchar(50),
  imei varchar(15) CHECK (imei ~ '^[0-9]{15}$'),
  esta_encendido boolean,
  checklist_estado jsonb,
  diagnostico_tecnico text,
  id_estado int NOT NULL,
  fecha_terminado timestamptz,
  fecha_entrega_cliente timestamptz,
  monto_cotizado decimal(12, 2) CHECK (
    monto_cotizado IS NULL
    OR monto_cotizado >= 0
  ),
  monto_descuento decimal(12, 2) NOT NULL DEFAULT 0 CHECK (monto_descuento >= 0),
  tipo_descuento varchar(20) CHECK (tipo_descuento IN ('porcentaje','monto_fijo')),
  justificacion_descuento text,
  fotos jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT chk_fechas_rep CHECK (
    (
      fecha_terminado IS NULL
      OR fecha_terminado >= fecha_ingreso
    )
    AND (
      fecha_entrega_cliente IS NULL
      OR (
        fecha_terminado IS NOT NULL
        AND fecha_entrega_cliente >= fecha_terminado
      )
    )
  )
);

CREATE TABLE Reparacion_Repuestos_Usados (
  id_repuesto_u INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_reparacion int NOT NULL,
  id_item int NOT NULL,
  cantidad int NOT NULL CHECK (cantidad > 0),
  precio_cobrado decimal(12, 2) NOT NULL CHECK (precio_cobrado >= 0),
  costo_unitario_momento decimal(12, 2) NOT NULL CHECK (costo_unitario_momento >= 0)
);

-- SEPTIMA PARTE

CREATE TABLE Garantias (
  id_garantia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta int,
  id_reparacion int,
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  estado varchar(20) NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa', 'vencida', 'invalidada')),
  motivo_invalidacion text,
  updated_at timestamptz DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_garantia_xor CHECK (
    (
      id_venta IS NOT NULL
      AND id_reparacion IS NULL
    )
    OR (
      id_venta IS NULL
      AND id_reparacion IS NOT NULL
    )
  ),
  CONSTRAINT chk_fechas_garantia CHECK (fecha_fin > fecha_inicio)
);

CREATE TABLE Pagos (
  id_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta int,
  id_reparacion int,
  metodo_pago varchar(30) NOT NULL CHECK (
    metodo_pago IN (
      'efectivo',
      'tarjeta',
      'transferencia',
      'yape',
      'plin',
      'otro'
    )
  ),
  monto decimal(12, 2) NOT NULL CHECK (monto > 0),
  es_adelanto boolean NOT NULL DEFAULT false,
  fecha_pago timestamptz NOT NULL DEFAULT now(),
  referencia_transaccion varchar(100),
  CONSTRAINT chk_pago_xor CHECK (
    (
      id_venta IS NOT NULL
      AND id_reparacion IS NULL
    )
    OR (
      id_venta IS NULL
      AND id_reparacion IS NOT NULL
    )
  ),
  CONSTRAINT chk_adelanto_solo_reparacion CHECK (
    es_adelanto = false
    OR id_reparacion IS NOT NULL
  )
);

CREATE TABLE Boletas (
  id_boleta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero varchar(20) NOT NULL UNIQUE,
  fecha_emision timestamptz NOT NULL DEFAULT now(),
  id_venta int,
  id_reparacion int,
  total decimal(12, 2) NOT NULL CHECK (total >= 0),
  estado varchar(20) NOT NULL DEFAULT 'emitida' CHECK (estado = 'emitida'),
  url_pdf varchar(500),
  CONSTRAINT chk_boleta_xor CHECK (
    (
      id_venta IS NOT NULL
      AND id_reparacion IS NULL
    )
    OR (
      id_venta IS NULL
      AND id_reparacion IS NOT NULL
    )
  )
);

-- OCTAVA PARTE

CREATE TABLE Logs_Sistema (
  id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_hora timestamptz NOT NULL DEFAULT now(),
  id_empleado int,
  id_sede int,
  tipo_accion varchar(20) NOT NULL CHECK (
    tipo_accion IN (
      'creacion',
      'actualizacion',
      'eliminacion',
      'cambio_estado',
      'cambio_precio',
      'login',
      'logout',
      'error',
      'anulacion'
    )
  ),
  tabla_afectada varchar(100) NOT NULL CHECK (
    tabla_afectada IN (
      'Sedes',
      'Empleados',
      'Clientes',
      'Items',
      'Inventario_Sedes',
      'Ventas',
      'Detalle_Venta',
      'Reparaciones',
      'Reparacion_Repuestos_Usados',
      'Compras_Refill',
      'Detalle_Compra_Refill',
      'Promociones',
      'Garantias',
      'Pagos',
      'Boletas',
      'Roles',
      'Empleado_Roles',
      'Marcas',
      'Categorias',
      'Proveedores',
      'Estados_Reparacion',
      'Cambios_Producto'
    )
  ),
  tipo_referencia varchar(30) CHECK (
    tipo_referencia IN (
      'venta',
      'compra',
      'reparacion',
      'ajuste',
      'promocion',
      'cambio',
      'otro'
    )
  ),
  id_referencia int,
  detalle_cambio text
);

-- Tabla de refresh tokens para revocación JWT server-side (HU-23)
CREATE TABLE RefreshTokens (
  id          BIGSERIAL PRIMARY KEY,
  id_empleado INTEGER NOT NULL,
  token_hash  TEXT NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  revoked     BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- NOVENA PARTE

-- === FK: RefreshTokens ===
ALTER TABLE RefreshTokens
ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado) ON DELETE CASCADE;

-- === FK: Empleados ===
ALTER TABLE Empleados
ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);
ALTER TABLE Empleados
ADD CONSTRAINT fk_empleados_rol FOREIGN KEY (id_rol) REFERENCES Roles(id_rol);

-- === FK: Items ===
ALTER TABLE Items
ADD FOREIGN KEY (id_marca) REFERENCES Marcas (id_marca);

-- === FK: Item_Categorias ===
ALTER TABLE Item_Categorias
ADD FOREIGN KEY (id_item) REFERENCES Items (id_item) ON DELETE CASCADE;
ALTER TABLE Item_Categorias
ADD FOREIGN KEY (id_categoria) REFERENCES Categorias (id_categoria) ON DELETE RESTRICT;

-- === FK: Inventario_Sedes ===
ALTER TABLE Inventario_Sedes
ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);
ALTER TABLE Inventario_Sedes
ADD FOREIGN KEY (id_item) REFERENCES Items (id_item);

-- === FK: Movimientos_Inventario ===
ALTER TABLE Movimientos_Inventario
ADD FOREIGN KEY (id_inventario) REFERENCES Inventario_Sedes (id_inventario);
ALTER TABLE Movimientos_Inventario
ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado);

-- === FK: Compras_Refill ===
ALTER TABLE Compras_Refill
ADD FOREIGN KEY (id_empleado_refiller) REFERENCES Empleados (id_empleado);
ALTER TABLE Compras_Refill
ADD FOREIGN KEY (id_sede_destino) REFERENCES Sedes (id_sede);
ALTER TABLE Compras_Refill
ADD FOREIGN KEY (id_proveedor) REFERENCES Proveedores (id_proveedor);

-- === FK: Detalle_Compra_Refill ===
ALTER TABLE Detalle_Compra_Refill
ADD FOREIGN KEY (id_compra) REFERENCES Compras_Refill (id_compra) ON DELETE CASCADE;
ALTER TABLE Detalle_Compra_Refill
ADD FOREIGN KEY (id_item) REFERENCES Items (id_item);

-- === FK: Promociones ===
ALTER TABLE Promociones
ADD FOREIGN KEY (id_categoria_afectada) REFERENCES Categorias (id_categoria);
ALTER TABLE Promociones
ADD FOREIGN KEY (id_item_afectado) REFERENCES Items (id_item);

-- === FK: Ventas ===
-- Razonamiento: ON DELETE SET NULL en id_cliente para preservar la venta si el cliente es eliminado.
ALTER TABLE Ventas
ADD FOREIGN KEY (id_cliente) REFERENCES Clientes (id_cliente) ON DELETE
SET NULL;
ALTER TABLE Ventas
ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado);
ALTER TABLE Ventas
ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);

-- === FK: Detalle_Venta ===
ALTER TABLE Detalle_Venta
ADD FOREIGN KEY (id_venta) REFERENCES Ventas (id_venta) ON DELETE CASCADE;
ALTER TABLE Detalle_Venta
ADD FOREIGN KEY (id_item) REFERENCES Items (id_item);

-- === FK: Reparaciones ===
ALTER TABLE Reparaciones
ADD FOREIGN KEY (id_estado) REFERENCES Estados_Reparacion (id_estado);
ALTER TABLE Reparaciones
ADD FOREIGN KEY (id_cliente) REFERENCES Clientes (id_cliente);
ALTER TABLE Reparaciones
ADD FOREIGN KEY (id_tecnico) REFERENCES Empleados (id_empleado);
ALTER TABLE Reparaciones
ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);

-- === FK: Reparacion_Repuestos_Usados ===
ALTER TABLE Reparacion_Repuestos_Usados
ADD FOREIGN KEY (id_reparacion) REFERENCES Reparaciones (id_reparacion) ON DELETE CASCADE;
ALTER TABLE Reparacion_Repuestos_Usados
ADD FOREIGN KEY (id_item) REFERENCES Items (id_item);

-- === FK: Garantias ===
ALTER TABLE Garantias
ADD FOREIGN KEY (id_venta) REFERENCES Ventas (id_venta) ON DELETE CASCADE;
ALTER TABLE Garantias
ADD FOREIGN KEY (id_reparacion) REFERENCES Reparaciones (id_reparacion) ON DELETE CASCADE;

-- === FK: Cambios_Producto ===
ALTER TABLE Cambios_Producto
ADD FOREIGN KEY (id_venta_origen) REFERENCES Ventas (id_venta);
ALTER TABLE Cambios_Producto
ADD FOREIGN KEY (id_garantia) REFERENCES Garantias (id_garantia) ON DELETE SET NULL;
ALTER TABLE Cambios_Producto
ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado);
ALTER TABLE Cambios_Producto
ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);
ALTER TABLE Cambios_Producto
ADD FOREIGN KEY (id_item_devuelto) REFERENCES Items (id_item);
ALTER TABLE Cambios_Producto
ADD FOREIGN KEY (id_item_entregado) REFERENCES Items (id_item);

-- === FK: Pagos ===
ALTER TABLE Pagos
ADD FOREIGN KEY (id_venta) REFERENCES Ventas (id_venta) ON DELETE CASCADE;
ALTER TABLE Pagos
ADD FOREIGN KEY (id_reparacion) REFERENCES Reparaciones (id_reparacion) ON DELETE CASCADE;

-- === FK: Boletas ===
ALTER TABLE Boletas
ADD FOREIGN KEY (id_venta) REFERENCES Ventas (id_venta) ON DELETE CASCADE;
ALTER TABLE Boletas
ADD FOREIGN KEY (id_reparacion) REFERENCES Reparaciones (id_reparacion) ON DELETE CASCADE;

-- === FK: Logs_Sistema ===
ALTER TABLE Logs_Sistema
ADD FOREIGN KEY (id_empleado) REFERENCES Empleados (id_empleado);
ALTER TABLE Logs_Sistema
ADD FOREIGN KEY (id_sede) REFERENCES Sedes (id_sede);

-- === FK: Sedes.created_by ===
-- ON DELETE SET NULL: si el Propietario creador es eliminado, el campo queda NULL sin perder la sede.
ALTER TABLE Sedes
ADD FOREIGN KEY (created_by) REFERENCES Empleados (id_empleado) ON DELETE SET NULL;

-- === FK: Empleados.created_by ===
-- Auto-referencial. ON DELETE SET NULL: eliminar al creador no elimina al empleado creado.
ALTER TABLE Empleados
ADD FOREIGN KEY (created_by) REFERENCES Empleados (id_empleado) ON DELETE SET NULL;


-- DECIMA PARTE

-- === Índices: Ventas ===
-- Consultas frecuentes: filtrar ventas por sede + rango de fechas (reportes diarios).
CREATE INDEX idx_ventas_sede_fecha ON Ventas (id_sede, fecha_emision);
-- Joins desde otras tablas (boletas, pagos, garantías) hacia Ventas por cliente.
CREATE INDEX idx_ventas_cliente ON Ventas (id_cliente);

-- === Índices: Detalle_Venta ===
-- Join principal: obtener líneas de una venta específica.
CREATE INDEX idx_detalle_venta_venta ON Detalle_Venta (id_venta);
-- Consultas de producto más vendido / análisis de rotación por item.
CREATE INDEX idx_det_venta_item ON Detalle_Venta (id_item);

-- === Índices: Inventario_Sedes ===
-- Búsqueda de stock de un item específico en todas las sedes.
CREATE INDEX idx_inv_item ON Inventario_Sedes (id_item);

-- === Índices: Reparaciones ===
-- Reportes de reparaciones por sede + fecha de ingreso.
CREATE INDEX idx_reparaciones_sede_fecha ON Reparaciones (id_sede, fecha_ingreso);
-- Dashboard de reparaciones por estado (pendientes, en proceso, terminadas).
CREATE INDEX idx_reparaciones_estado ON Reparaciones (id_estado);
-- Historial de reparaciones por cliente.
CREATE INDEX idx_reparaciones_cliente ON Reparaciones (id_cliente);
-- Carga de trabajo por técnico.
CREATE INDEX idx_reparaciones_tecnico ON Reparaciones (id_tecnico);

-- === Índices: Reparacion_Repuestos_Usados ===
-- Análisis de repuestos más usados en reparaciones.
CREATE INDEX idx_rep_rep_usados_item ON Reparacion_Repuestos_Usados (id_item);

-- === Índices: Logs_Sistema ===
-- Consultas de auditoría por rango de fechas.
CREATE INDEX idx_logs_fecha_hora ON Logs_Sistema (fecha_hora);
-- Trazabilidad: buscar todos los logs de una entidad específica (ej: logs de la venta #123).
CREATE INDEX idx_logs_ref ON Logs_Sistema (tipo_referencia, id_referencia);

-- === Índices: Movimientos_Inventario ===
-- Auditoría de movimientos por fecha.
CREATE INDEX idx_mov_inv_fecha ON Movimientos_Inventario (fecha_movimiento);
-- Trazabilidad de stock: historial de movimientos de un registro de inventario específico.
CREATE INDEX idx_mov_inv_inventario ON Movimientos_Inventario (id_inventario, fecha_movimiento);

-- === Índices: Items ===
-- Búsqueda por modelo dentro del JSON de especificaciones (ej: "todos los items para iPhone 14").
CREATE INDEX idx_item_espec_modelo ON Items ((especificaciones->>'modelo'));

-- === Índices: Detalle_Compra_Refill ===
-- Análisis de compras por item (costo histórico, proveedores).
CREATE INDEX idx_det_compra_item ON Detalle_Compra_Refill (id_item);

-- === Índices: Pagos (parciales, solo filas con FK no nula) ===
-- Pagos asociados a una venta específica.
CREATE INDEX idx_pagos_venta ON Pagos (id_venta)
WHERE id_venta IS NOT NULL;
-- Pagos asociados a una reparación específica (incluye adelantos).
CREATE INDEX idx_pagos_reparacion ON Pagos (id_reparacion)
WHERE id_reparacion IS NOT NULL;

-- === Índices: Garantias (parciales, solo filas con FK no nula) ===
-- Garantías de una venta específica.
CREATE INDEX idx_garantias_venta ON Garantias (id_venta)
WHERE id_venta IS NOT NULL;
-- Garantías de una reparación específica.
CREATE INDEX idx_garantias_reparacion ON Garantias (id_reparacion)
WHERE id_reparacion IS NOT NULL;

-- === Índices: Boletas (parciales, solo filas con FK no nula) ===
-- Boletas emitidas para una venta.
CREATE INDEX idx_boletas_venta ON Boletas (id_venta)
WHERE id_venta IS NOT NULL;
-- Boletas emitidas para una reparación.
CREATE INDEX idx_boletas_reparacion ON Boletas (id_reparacion)
WHERE id_reparacion IS NOT NULL;

-- === Índices: Cambios_Producto ===
CREATE INDEX idx_cambios_venta_origen ON Cambios_Producto (id_venta_origen);
CREATE INDEX idx_cambios_sede_fecha ON Cambios_Producto (id_sede, fecha_cambio);
CREATE INDEX idx_cambios_item_devuelto ON Cambios_Producto (id_item_devuelto);
CREATE INDEX idx_cambios_item_entregado ON Cambios_Producto (id_item_entregado);

-- === Índices: RefreshTokens ===
-- Búsqueda de tokens activos por empleado (login / logout / refresh).
CREATE INDEX idx_refresh_tokens_empleado ON RefreshTokens (id_empleado);
-- Limpieza periódica de tokens expirados no revocados.
CREATE INDEX idx_refresh_tokens_expiry ON RefreshTokens (expires_at)
WHERE revoked = false;